replicaCount: 1

image:
  repository: a1
  tag: latest
  pullPolicy: Never

# name of the secret that allows for privagte registry docker pulls.
# if the value is "lfhelper", there is a helper function included in this chart, and it uses imageCredentials .
# imageCredentials is referenced in secrets.yaml, and uses a helper function to formulate the docker reg username and password into a valid dockerconfig.json.
# This is the service for A1's external facing HTTP API
httpservice:
  name: a1httpservice
  port: 10000 # This is hardcoded in a1, probably dangerous to change
  type: ClusterIP

# This is the service for rmr between A1 and the xapps
rmrservice:
  name: a1rmrservice
  port: 4562 # This is hardcoded in a1, probably dangerous to change
  type: ClusterIP

# This is the service for the "hidden" port 4561 that rmr listens on for route manager
rmrrtemgrservice:
  name: a1rmrrtemgrservice
  port: 4561 # This is hardcoded in rmr, probably dangerous to change
  type: ClusterIP

# these are ENV variables that A1 takes; see docs
rmr_timeout_config:
  rcv_retry_times: 20
