# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secondary_rat_data_usage_report.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='secondary_rat_data_usage_report.proto',
  package='streaming_protobufs',
  syntax='proto3',
  serialized_options=_b('Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufs'),
  serialized_pb=_b('\n%secondary_rat_data_usage_report.proto\x12\x13streaming_protobufs\x1a\x1egoogle/protobuf/wrappers.proto\"h\n\x1bSecondaryRATDataUsageReport\x12I\n\x0bprotocolIEs\x18\x01 \x01(\x0b\x32\x34.streaming_protobufs.SecondaryRATDataUsageReport_IEs\"\xf7\x01\n\x1fSecondaryRATDataUsageReport_IEs\x12\x1a\n\x12id_MeNB_UE_X2AP_ID\x18\x01 \x01(\r\x12\x1a\n\x12id_SgNB_UE_X2AP_ID\x18\x02 \x01(\r\x12X\n\x1eid_SecondaryRATUsageReportList\x18\x03 \x01(\x0b\x32\x30.streaming_protobufs.SecondaryRATUsageReportList\x12\x42\n\x1cid_MeNB_UE_X2AP_ID_Extension\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\"b\n\x1bSecondaryRATUsageReportList\x12\x43\n\x05items\x18\x01 \x03(\x0b\x32\x34.streaming_protobufs.SecondaryRATUsageReport_ItemIEs\"}\n\x1fSecondaryRATUsageReport_ItemIEs\x12Z\n\x1fid_SecondaryRATUsageReport_Item\x18\x01 \x01(\x0b\x32\x31.streaming_protobufs.SecondaryRATUsageReport_Item\"\x8d\x02\n\x1cSecondaryRATUsageReport_Item\x12\x10\n\x08\x65_RAB_ID\x18\x01 \x01(\r\x12\\\n\x10secondaryRATType\x18\x02 \x01(\x0e\x32\x42.streaming_protobufs.SecondaryRATUsageReport_Item.SecondaryRATType\x12G\n\x14\x65_RABUsageReportList\x18\x03 \x01(\x0b\x32).streaming_protobufs.E_RABUsageReportList\"4\n\x10SecondaryRATType\x12\x18\n\x14protobuf_unspecified\x10\x00\x12\x06\n\x02nr\x10\x01\"T\n\x14\x45_RABUsageReportList\x12<\n\x05items\x18\x01 \x03(\x0b\x32-.streaming_protobufs.E_RABUsageReport_ItemIEs\"h\n\x18\x45_RABUsageReport_ItemIEs\x12L\n\x18id_E_RABUsageReport_Item\x18\x01 \x01(\x0b\x32*.streaming_protobufs.E_RABUsageReport_Item\"q\n\x15\x45_RABUsageReport_Item\x12\x16\n\x0estartTimeStamp\x18\x01 \x01(\x04\x12\x14\n\x0c\x65ndTimeStamp\x18\x02 \x01(\x04\x12\x14\n\x0cusageCountUL\x18\x03 \x01(\x04\x12\x14\n\x0cusageCountDL\x18\x04 \x01(\x04\x42\x33Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])



_SECONDARYRATUSAGEREPORT_ITEM_SECONDARYRATTYPE = _descriptor.EnumDescriptor(
  name='SecondaryRATType',
  full_name='streaming_protobufs.SecondaryRATUsageReport_Item.SecondaryRATType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='protobuf_unspecified', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='nr', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=895,
  serialized_end=947,
)
_sym_db.RegisterEnumDescriptor(_SECONDARYRATUSAGEREPORT_ITEM_SECONDARYRATTYPE)


_SECONDARYRATDATAUSAGEREPORT = _descriptor.Descriptor(
  name='SecondaryRATDataUsageReport',
  full_name='streaming_protobufs.SecondaryRATDataUsageReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocolIEs', full_name='streaming_protobufs.SecondaryRATDataUsageReport.protocolIEs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=198,
)


_SECONDARYRATDATAUSAGEREPORT_IES = _descriptor.Descriptor(
  name='SecondaryRATDataUsageReport_IEs',
  full_name='streaming_protobufs.SecondaryRATDataUsageReport_IEs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID', full_name='streaming_protobufs.SecondaryRATDataUsageReport_IEs.id_MeNB_UE_X2AP_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_SgNB_UE_X2AP_ID', full_name='streaming_protobufs.SecondaryRATDataUsageReport_IEs.id_SgNB_UE_X2AP_ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_SecondaryRATUsageReportList', full_name='streaming_protobufs.SecondaryRATDataUsageReport_IEs.id_SecondaryRATUsageReportList', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID_Extension', full_name='streaming_protobufs.SecondaryRATDataUsageReport_IEs.id_MeNB_UE_X2AP_ID_Extension', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=448,
)


_SECONDARYRATUSAGEREPORTLIST = _descriptor.Descriptor(
  name='SecondaryRATUsageReportList',
  full_name='streaming_protobufs.SecondaryRATUsageReportList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='streaming_protobufs.SecondaryRATUsageReportList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=548,
)


_SECONDARYRATUSAGEREPORT_ITEMIES = _descriptor.Descriptor(
  name='SecondaryRATUsageReport_ItemIEs',
  full_name='streaming_protobufs.SecondaryRATUsageReport_ItemIEs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_SecondaryRATUsageReport_Item', full_name='streaming_protobufs.SecondaryRATUsageReport_ItemIEs.id_SecondaryRATUsageReport_Item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=675,
)


_SECONDARYRATUSAGEREPORT_ITEM = _descriptor.Descriptor(
  name='SecondaryRATUsageReport_Item',
  full_name='streaming_protobufs.SecondaryRATUsageReport_Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e_RAB_ID', full_name='streaming_protobufs.SecondaryRATUsageReport_Item.e_RAB_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secondaryRATType', full_name='streaming_protobufs.SecondaryRATUsageReport_Item.secondaryRATType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='e_RABUsageReportList', full_name='streaming_protobufs.SecondaryRATUsageReport_Item.e_RABUsageReportList', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SECONDARYRATUSAGEREPORT_ITEM_SECONDARYRATTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=947,
)


_E_RABUSAGEREPORTLIST = _descriptor.Descriptor(
  name='E_RABUsageReportList',
  full_name='streaming_protobufs.E_RABUsageReportList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='streaming_protobufs.E_RABUsageReportList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=949,
  serialized_end=1033,
)


_E_RABUSAGEREPORT_ITEMIES = _descriptor.Descriptor(
  name='E_RABUsageReport_ItemIEs',
  full_name='streaming_protobufs.E_RABUsageReport_ItemIEs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_E_RABUsageReport_Item', full_name='streaming_protobufs.E_RABUsageReport_ItemIEs.id_E_RABUsageReport_Item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1035,
  serialized_end=1139,
)


_E_RABUSAGEREPORT_ITEM = _descriptor.Descriptor(
  name='E_RABUsageReport_Item',
  full_name='streaming_protobufs.E_RABUsageReport_Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTimeStamp', full_name='streaming_protobufs.E_RABUsageReport_Item.startTimeStamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTimeStamp', full_name='streaming_protobufs.E_RABUsageReport_Item.endTimeStamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usageCountUL', full_name='streaming_protobufs.E_RABUsageReport_Item.usageCountUL', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usageCountDL', full_name='streaming_protobufs.E_RABUsageReport_Item.usageCountDL', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1141,
  serialized_end=1254,
)

_SECONDARYRATDATAUSAGEREPORT.fields_by_name['protocolIEs'].message_type = _SECONDARYRATDATAUSAGEREPORT_IES
_SECONDARYRATDATAUSAGEREPORT_IES.fields_by_name['id_SecondaryRATUsageReportList'].message_type = _SECONDARYRATUSAGEREPORTLIST
_SECONDARYRATDATAUSAGEREPORT_IES.fields_by_name['id_MeNB_UE_X2AP_ID_Extension'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
_SECONDARYRATUSAGEREPORTLIST.fields_by_name['items'].message_type = _SECONDARYRATUSAGEREPORT_ITEMIES
_SECONDARYRATUSAGEREPORT_ITEMIES.fields_by_name['id_SecondaryRATUsageReport_Item'].message_type = _SECONDARYRATUSAGEREPORT_ITEM
_SECONDARYRATUSAGEREPORT_ITEM.fields_by_name['secondaryRATType'].enum_type = _SECONDARYRATUSAGEREPORT_ITEM_SECONDARYRATTYPE
_SECONDARYRATUSAGEREPORT_ITEM.fields_by_name['e_RABUsageReportList'].message_type = _E_RABUSAGEREPORTLIST
_SECONDARYRATUSAGEREPORT_ITEM_SECONDARYRATTYPE.containing_type = _SECONDARYRATUSAGEREPORT_ITEM
_E_RABUSAGEREPORTLIST.fields_by_name['items'].message_type = _E_RABUSAGEREPORT_ITEMIES
_E_RABUSAGEREPORT_ITEMIES.fields_by_name['id_E_RABUsageReport_Item'].message_type = _E_RABUSAGEREPORT_ITEM
DESCRIPTOR.message_types_by_name['SecondaryRATDataUsageReport'] = _SECONDARYRATDATAUSAGEREPORT
DESCRIPTOR.message_types_by_name['SecondaryRATDataUsageReport_IEs'] = _SECONDARYRATDATAUSAGEREPORT_IES
DESCRIPTOR.message_types_by_name['SecondaryRATUsageReportList'] = _SECONDARYRATUSAGEREPORTLIST
DESCRIPTOR.message_types_by_name['SecondaryRATUsageReport_ItemIEs'] = _SECONDARYRATUSAGEREPORT_ITEMIES
DESCRIPTOR.message_types_by_name['SecondaryRATUsageReport_Item'] = _SECONDARYRATUSAGEREPORT_ITEM
DESCRIPTOR.message_types_by_name['E_RABUsageReportList'] = _E_RABUSAGEREPORTLIST
DESCRIPTOR.message_types_by_name['E_RABUsageReport_ItemIEs'] = _E_RABUSAGEREPORT_ITEMIES
DESCRIPTOR.message_types_by_name['E_RABUsageReport_Item'] = _E_RABUSAGEREPORT_ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecondaryRATDataUsageReport = _reflection.GeneratedProtocolMessageType('SecondaryRATDataUsageReport', (_message.Message,), {
  'DESCRIPTOR' : _SECONDARYRATDATAUSAGEREPORT,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SecondaryRATDataUsageReport)
  })
_sym_db.RegisterMessage(SecondaryRATDataUsageReport)

SecondaryRATDataUsageReport_IEs = _reflection.GeneratedProtocolMessageType('SecondaryRATDataUsageReport_IEs', (_message.Message,), {
  'DESCRIPTOR' : _SECONDARYRATDATAUSAGEREPORT_IES,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SecondaryRATDataUsageReport_IEs)
  })
_sym_db.RegisterMessage(SecondaryRATDataUsageReport_IEs)

SecondaryRATUsageReportList = _reflection.GeneratedProtocolMessageType('SecondaryRATUsageReportList', (_message.Message,), {
  'DESCRIPTOR' : _SECONDARYRATUSAGEREPORTLIST,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SecondaryRATUsageReportList)
  })
_sym_db.RegisterMessage(SecondaryRATUsageReportList)

SecondaryRATUsageReport_ItemIEs = _reflection.GeneratedProtocolMessageType('SecondaryRATUsageReport_ItemIEs', (_message.Message,), {
  'DESCRIPTOR' : _SECONDARYRATUSAGEREPORT_ITEMIES,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SecondaryRATUsageReport_ItemIEs)
  })
_sym_db.RegisterMessage(SecondaryRATUsageReport_ItemIEs)

SecondaryRATUsageReport_Item = _reflection.GeneratedProtocolMessageType('SecondaryRATUsageReport_Item', (_message.Message,), {
  'DESCRIPTOR' : _SECONDARYRATUSAGEREPORT_ITEM,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SecondaryRATUsageReport_Item)
  })
_sym_db.RegisterMessage(SecondaryRATUsageReport_Item)

E_RABUsageReportList = _reflection.GeneratedProtocolMessageType('E_RABUsageReportList', (_message.Message,), {
  'DESCRIPTOR' : _E_RABUSAGEREPORTLIST,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.E_RABUsageReportList)
  })
_sym_db.RegisterMessage(E_RABUsageReportList)

E_RABUsageReport_ItemIEs = _reflection.GeneratedProtocolMessageType('E_RABUsageReport_ItemIEs', (_message.Message,), {
  'DESCRIPTOR' : _E_RABUSAGEREPORT_ITEMIES,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.E_RABUsageReport_ItemIEs)
  })
_sym_db.RegisterMessage(E_RABUsageReport_ItemIEs)

E_RABUsageReport_Item = _reflection.GeneratedProtocolMessageType('E_RABUsageReport_Item', (_message.Message,), {
  'DESCRIPTOR' : _E_RABUSAGEREPORT_ITEM,
  '__module__' : 'secondary_rat_data_usage_report_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.E_RABUsageReport_Item)
  })
_sym_db.RegisterMessage(E_RABUsageReport_Item)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
