# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgnb_change_required.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import rrc_cg_config_pb2 as rrc__cg__config__pb2
import error_cause_pb2 as error__cause__pb2
import x2ap_common_types_pb2 as x2ap__common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgnb_change_required.proto',
  package='streaming_protobufs',
  syntax='proto3',
  serialized_options=_b('Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufs'),
  serialized_pb=_b('\n\x1asgnb_change_required.proto\x12\x13streaming_protobufs\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13rrc_cg_config.proto\x1a\x11\x65rror_cause.proto\x1a\x17x2ap_common_types.proto\"V\n\x12SgNBChangeRequired\x12@\n\x0bprotocolIEs\x18\x01 \x01(\x0b\x32+.streaming_protobufs.SgNBChangeRequired_IEs\"\xc0\x02\n\x16SgNBChangeRequired_IEs\x12\x1a\n\x12id_MeNB_UE_X2AP_ID\x18\x01 \x01(\r\x12\x1a\n\x12id_SgNB_UE_X2AP_ID\x18\x02 \x01(\r\x12<\n\x11id_Target_SgNB_ID\x18\x03 \x01(\x0b\x32!.streaming_protobufs.GlobalGNB_ID\x12,\n\x08id_Cause\x18\x04 \x01(\x0b\x32\x1a.streaming_protobufs.Cause\x12>\n\x16id_SgNBtoMeNBContainer\x18\x05 \x01(\x0b\x32\x1e.streaming_protobufs.CG_Config\x12\x42\n\x1cid_MeNB_UE_X2AP_ID_Extension\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueB3Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,rrc__cg__config__pb2.DESCRIPTOR,error__cause__pb2.DESCRIPTOR,x2ap__common__types__pb2.DESCRIPTOR,])




_SGNBCHANGEREQUIRED = _descriptor.Descriptor(
  name='SgNBChangeRequired',
  full_name='streaming_protobufs.SgNBChangeRequired',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocolIEs', full_name='streaming_protobufs.SgNBChangeRequired.protocolIEs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=234,
)


_SGNBCHANGEREQUIRED_IES = _descriptor.Descriptor(
  name='SgNBChangeRequired_IEs',
  full_name='streaming_protobufs.SgNBChangeRequired_IEs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_MeNB_UE_X2AP_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_SgNB_UE_X2AP_ID', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_SgNB_UE_X2AP_ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_Target_SgNB_ID', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_Target_SgNB_ID', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_Cause', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_Cause', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_SgNBtoMeNBContainer', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_SgNBtoMeNBContainer', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID_Extension', full_name='streaming_protobufs.SgNBChangeRequired_IEs.id_MeNB_UE_X2AP_ID_Extension', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=557,
)

_SGNBCHANGEREQUIRED.fields_by_name['protocolIEs'].message_type = _SGNBCHANGEREQUIRED_IES
_SGNBCHANGEREQUIRED_IES.fields_by_name['id_Target_SgNB_ID'].message_type = x2ap__common__types__pb2._GLOBALGNB_ID
_SGNBCHANGEREQUIRED_IES.fields_by_name['id_Cause'].message_type = error__cause__pb2._CAUSE
_SGNBCHANGEREQUIRED_IES.fields_by_name['id_SgNBtoMeNBContainer'].message_type = rrc__cg__config__pb2._CG_CONFIG
_SGNBCHANGEREQUIRED_IES.fields_by_name['id_MeNB_UE_X2AP_ID_Extension'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['SgNBChangeRequired'] = _SGNBCHANGEREQUIRED
DESCRIPTOR.message_types_by_name['SgNBChangeRequired_IEs'] = _SGNBCHANGEREQUIRED_IES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SgNBChangeRequired = _reflection.GeneratedProtocolMessageType('SgNBChangeRequired', (_message.Message,), {
  'DESCRIPTOR' : _SGNBCHANGEREQUIRED,
  '__module__' : 'sgnb_change_required_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SgNBChangeRequired)
  })
_sym_db.RegisterMessage(SgNBChangeRequired)

SgNBChangeRequired_IEs = _reflection.GeneratedProtocolMessageType('SgNBChangeRequired_IEs', (_message.Message,), {
  'DESCRIPTOR' : _SGNBCHANGEREQUIRED_IES,
  '__module__' : 'sgnb_change_required_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SgNBChangeRequired_IEs)
  })
_sym_db.RegisterMessage(SgNBChangeRequired_IEs)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
