# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgnb_change_refuse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import error_cause_pb2 as error__cause__pb2
import x2ap_common_types_pb2 as x2ap__common__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgnb_change_refuse.proto',
  package='streaming_protobufs',
  syntax='proto3',
  serialized_options=_b('Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufs'),
  serialized_pb=_b('\n\x18sgnb_change_refuse.proto\x12\x13streaming_protobufs\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11\x65rror_cause.proto\x1a\x17x2ap_common_types.proto\"\x8c\x02\n\x10SgNBChangeRefuse\x12\x1a\n\x12id_MeNB_UE_X2AP_ID\x18\x01 \x01(\r\x12\x1a\n\x12id_SgNB_UE_X2AP_ID\x18\x02 \x01(\r\x12,\n\x08id_Cause\x18\x03 \x01(\x0b\x32\x1a.streaming_protobufs.Cause\x12N\n\x19id_CriticalityDiagnostics\x18\x04 \x01(\x0b\x32+.streaming_protobufs.CriticalityDiagnostics\x12\x42\n\x1cid_MeNB_UE_X2AP_ID_Extension\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.UInt32ValueB3Z1gerrit.o-ran-sc.org/r/ric-plt/streaming-protobufsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,error__cause__pb2.DESCRIPTOR,x2ap__common__types__pb2.DESCRIPTOR,])




_SGNBCHANGEREFUSE = _descriptor.Descriptor(
  name='SgNBChangeRefuse',
  full_name='streaming_protobufs.SgNBChangeRefuse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID', full_name='streaming_protobufs.SgNBChangeRefuse.id_MeNB_UE_X2AP_ID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_SgNB_UE_X2AP_ID', full_name='streaming_protobufs.SgNBChangeRefuse.id_SgNB_UE_X2AP_ID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_Cause', full_name='streaming_protobufs.SgNBChangeRefuse.id_Cause', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_CriticalityDiagnostics', full_name='streaming_protobufs.SgNBChangeRefuse.id_CriticalityDiagnostics', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_MeNB_UE_X2AP_ID_Extension', full_name='streaming_protobufs.SgNBChangeRefuse.id_MeNB_UE_X2AP_ID_Extension', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=394,
)

_SGNBCHANGEREFUSE.fields_by_name['id_Cause'].message_type = error__cause__pb2._CAUSE
_SGNBCHANGEREFUSE.fields_by_name['id_CriticalityDiagnostics'].message_type = x2ap__common__types__pb2._CRITICALITYDIAGNOSTICS
_SGNBCHANGEREFUSE.fields_by_name['id_MeNB_UE_X2AP_ID_Extension'].message_type = google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE
DESCRIPTOR.message_types_by_name['SgNBChangeRefuse'] = _SGNBCHANGEREFUSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SgNBChangeRefuse = _reflection.GeneratedProtocolMessageType('SgNBChangeRefuse', (_message.Message,), {
  'DESCRIPTOR' : _SGNBCHANGEREFUSE,
  '__module__' : 'sgnb_change_refuse_pb2'
  # @@protoc_insertion_point(class_scope:streaming_protobufs.SgNBChangeRefuse)
  })
_sym_db.RegisterMessage(SgNBChangeRefuse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
