/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: error_cause.proto */

#ifndef PROTOBUF_C_error_5fcause_2eproto__INCLUDED
#define PROTOBUF_C_error_5fcause_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _StreamingProtobufs__Cause StreamingProtobufs__Cause;
typedef struct _StreamingProtobufs__CauseRadioNetwork StreamingProtobufs__CauseRadioNetwork;
typedef struct _StreamingProtobufs__CauseTransport StreamingProtobufs__CauseTransport;
typedef struct _StreamingProtobufs__CauseProtocol StreamingProtobufs__CauseProtocol;
typedef struct _StreamingProtobufs__CauseMisc StreamingProtobufs__CauseMisc;


/* --- enums --- */

typedef enum _StreamingProtobufs__CauseRadioNetwork__Value {
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__protobuf_unspecified = 0,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__handover_desirable_for_radio_reasons = 1,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__time_critical_handover = 2,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__resource_optimisation_handover = 3,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__reduce_load_in_serving_cell = 4,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__partial_handover = 5,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_new_eNB_UE_X2AP_ID = 6,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_old_eNB_UE_X2AP_ID = 7,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_pair_of_UE_X2AP_ID = 8,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__ho_target_not_allowed = 9,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__tx2relocoverall_expiry = 10,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__trelocprep_expiry = 11,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__cell_not_available = 12,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__no_radio_resources_available_in_target_cell = 13,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__invalid_MME_GroupID = 14,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_MME_Code = 15,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__encryption_and_or_integrity_protection_algorithms_not_supported = 16,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__reportCharacteristicsEmpty = 17,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__noReportPeriodicity = 18,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__existingMeasurementID = 19,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_eNB_Measurement_ID = 20,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__measurement_temporarily_not_available = 21,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unspecified = 22,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__load_balancing = 23,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__handover_optimisation = 24,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__value_out_of_allowed_range = 25,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__multiple_E_RAB_ID_instances = 26,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__switch_off_ongoing = 27,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__not_supported_QCI_value = 28,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__measurement_not_supported_for_the_object = 29,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__tDCoverall_expiry = 30,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__tDCprep_expiry = 31,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__action_desirable_for_radio_reasons = 32,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__reduce_load = 33,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__resource_optimisation = 34,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__time_critical_action = 35,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__target_not_allowed = 36,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__no_radio_resources_available = 37,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__invalid_QoS_combination = 38,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__encryption_algorithms_not_aupported = 39,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__procedure_cancelled = 40,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__rRM_purpose = 41,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__improve_user_bit_rate = 42,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__user_inactivity = 43,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__radio_connection_with_UE_lost = 44,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__failure_in_the_radio_interface_procedure = 45,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__bearer_option_not_supported = 46,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__mCG_Mobility = 47,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__sCG_Mobility = 48,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__count_reaches_max_value = 49,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__unknown_old_en_gNB_UE_X2AP_ID = 50,
  STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__pDCP_Overload = 51
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE)
} StreamingProtobufs__CauseRadioNetwork__Value;
typedef enum _StreamingProtobufs__CauseTransport__Value {
  STREAMING_PROTOBUFS__CAUSE_TRANSPORT__VALUE__protobuf_unspecified = 0,
  STREAMING_PROTOBUFS__CAUSE_TRANSPORT__VALUE__transport_resource_unavailable = 1,
  STREAMING_PROTOBUFS__CAUSE_TRANSPORT__VALUE__unspecified = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__CAUSE_TRANSPORT__VALUE)
} StreamingProtobufs__CauseTransport__Value;
typedef enum _StreamingProtobufs__CauseProtocol__Value {
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__protobuf_unspecified = 0,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__transfer_syntax_error = 1,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__abstract_syntax_error_reject = 2,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__abstract_syntax_error_ignore_and_notify = 3,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__message_not_compatible_with_receiver_state = 4,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__semantic_error = 5,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__unspecified = 6,
  STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__abstract_syntax_error_falsely_constructed_message = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE)
} StreamingProtobufs__CauseProtocol__Value;
typedef enum _StreamingProtobufs__CauseMisc__Value {
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__protobuf_unspecified = 0,
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__control_processing_overload = 1,
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__hardware_failure = 2,
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__om_intervention = 3,
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__not_enough_user_plane_processing_resources = 4,
  STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__unspecified = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__CAUSE_MISC__VALUE)
} StreamingProtobufs__CauseMisc__Value;

/* --- messages --- */

typedef enum {
  STREAMING_PROTOBUFS__CAUSE__VALUE__NOT_SET = 0,
  STREAMING_PROTOBUFS__CAUSE__VALUE_RADIO_NETWORK = 1,
  STREAMING_PROTOBUFS__CAUSE__VALUE_TRANSPORT = 2,
  STREAMING_PROTOBUFS__CAUSE__VALUE_PROTOCOL = 3,
  STREAMING_PROTOBUFS__CAUSE__VALUE_MISC = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__CAUSE__VALUE)
} StreamingProtobufs__Cause__ValueCase;

struct  _StreamingProtobufs__Cause
{
  ProtobufCMessage base;
  StreamingProtobufs__Cause__ValueCase value_case;
  union {
    StreamingProtobufs__CauseRadioNetwork *radionetwork;
    StreamingProtobufs__CauseTransport *transport;
    StreamingProtobufs__CauseProtocol *protocol;
    StreamingProtobufs__CauseMisc *misc;
  };
};
#define STREAMING_PROTOBUFS__CAUSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__cause__descriptor) \
    , STREAMING_PROTOBUFS__CAUSE__VALUE__NOT_SET, {0} }


struct  _StreamingProtobufs__CauseRadioNetwork
{
  ProtobufCMessage base;
  StreamingProtobufs__CauseRadioNetwork__Value value;
};
#define STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__cause_radio_network__descriptor) \
    , STREAMING_PROTOBUFS__CAUSE_RADIO_NETWORK__VALUE__protobuf_unspecified }


struct  _StreamingProtobufs__CauseTransport
{
  ProtobufCMessage base;
  StreamingProtobufs__CauseTransport__Value value;
};
#define STREAMING_PROTOBUFS__CAUSE_TRANSPORT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__cause_transport__descriptor) \
    , STREAMING_PROTOBUFS__CAUSE_TRANSPORT__VALUE__protobuf_unspecified }


struct  _StreamingProtobufs__CauseProtocol
{
  ProtobufCMessage base;
  StreamingProtobufs__CauseProtocol__Value value;
};
#define STREAMING_PROTOBUFS__CAUSE_PROTOCOL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__cause_protocol__descriptor) \
    , STREAMING_PROTOBUFS__CAUSE_PROTOCOL__VALUE__protobuf_unspecified }


struct  _StreamingProtobufs__CauseMisc
{
  ProtobufCMessage base;
  StreamingProtobufs__CauseMisc__Value value;
};
#define STREAMING_PROTOBUFS__CAUSE_MISC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__cause_misc__descriptor) \
    , STREAMING_PROTOBUFS__CAUSE_MISC__VALUE__protobuf_unspecified }


/* StreamingProtobufs__Cause methods */
void   streaming_protobufs__cause__init
                     (StreamingProtobufs__Cause         *message);
size_t streaming_protobufs__cause__get_packed_size
                     (const StreamingProtobufs__Cause   *message);
size_t streaming_protobufs__cause__pack
                     (const StreamingProtobufs__Cause   *message,
                      uint8_t             *out);
size_t streaming_protobufs__cause__pack_to_buffer
                     (const StreamingProtobufs__Cause   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__Cause *
       streaming_protobufs__cause__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__cause__free_unpacked
                     (StreamingProtobufs__Cause *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__CauseRadioNetwork methods */
void   streaming_protobufs__cause_radio_network__init
                     (StreamingProtobufs__CauseRadioNetwork         *message);
size_t streaming_protobufs__cause_radio_network__get_packed_size
                     (const StreamingProtobufs__CauseRadioNetwork   *message);
size_t streaming_protobufs__cause_radio_network__pack
                     (const StreamingProtobufs__CauseRadioNetwork   *message,
                      uint8_t             *out);
size_t streaming_protobufs__cause_radio_network__pack_to_buffer
                     (const StreamingProtobufs__CauseRadioNetwork   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__CauseRadioNetwork *
       streaming_protobufs__cause_radio_network__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__cause_radio_network__free_unpacked
                     (StreamingProtobufs__CauseRadioNetwork *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__CauseTransport methods */
void   streaming_protobufs__cause_transport__init
                     (StreamingProtobufs__CauseTransport         *message);
size_t streaming_protobufs__cause_transport__get_packed_size
                     (const StreamingProtobufs__CauseTransport   *message);
size_t streaming_protobufs__cause_transport__pack
                     (const StreamingProtobufs__CauseTransport   *message,
                      uint8_t             *out);
size_t streaming_protobufs__cause_transport__pack_to_buffer
                     (const StreamingProtobufs__CauseTransport   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__CauseTransport *
       streaming_protobufs__cause_transport__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__cause_transport__free_unpacked
                     (StreamingProtobufs__CauseTransport *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__CauseProtocol methods */
void   streaming_protobufs__cause_protocol__init
                     (StreamingProtobufs__CauseProtocol         *message);
size_t streaming_protobufs__cause_protocol__get_packed_size
                     (const StreamingProtobufs__CauseProtocol   *message);
size_t streaming_protobufs__cause_protocol__pack
                     (const StreamingProtobufs__CauseProtocol   *message,
                      uint8_t             *out);
size_t streaming_protobufs__cause_protocol__pack_to_buffer
                     (const StreamingProtobufs__CauseProtocol   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__CauseProtocol *
       streaming_protobufs__cause_protocol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__cause_protocol__free_unpacked
                     (StreamingProtobufs__CauseProtocol *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__CauseMisc methods */
void   streaming_protobufs__cause_misc__init
                     (StreamingProtobufs__CauseMisc         *message);
size_t streaming_protobufs__cause_misc__get_packed_size
                     (const StreamingProtobufs__CauseMisc   *message);
size_t streaming_protobufs__cause_misc__pack
                     (const StreamingProtobufs__CauseMisc   *message,
                      uint8_t             *out);
size_t streaming_protobufs__cause_misc__pack_to_buffer
                     (const StreamingProtobufs__CauseMisc   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__CauseMisc *
       streaming_protobufs__cause_misc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__cause_misc__free_unpacked
                     (StreamingProtobufs__CauseMisc *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StreamingProtobufs__Cause_Closure)
                 (const StreamingProtobufs__Cause *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__CauseRadioNetwork_Closure)
                 (const StreamingProtobufs__CauseRadioNetwork *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__CauseTransport_Closure)
                 (const StreamingProtobufs__CauseTransport *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__CauseProtocol_Closure)
                 (const StreamingProtobufs__CauseProtocol *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__CauseMisc_Closure)
                 (const StreamingProtobufs__CauseMisc *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor streaming_protobufs__cause__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__cause_radio_network__descriptor;
extern const ProtobufCEnumDescriptor    streaming_protobufs__cause_radio_network__value__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__cause_transport__descriptor;
extern const ProtobufCEnumDescriptor    streaming_protobufs__cause_transport__value__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__cause_protocol__descriptor;
extern const ProtobufCEnumDescriptor    streaming_protobufs__cause_protocol__value__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__cause_misc__descriptor;
extern const ProtobufCEnumDescriptor    streaming_protobufs__cause_misc__value__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_error_5fcause_2eproto__INCLUDED */
