/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rrc_reconfiguration.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rrc_reconfiguration.pb-c.h"
void   streaming_protobufs__rrcreconfiguration__init
                     (StreamingProtobufs__RRCReconfiguration         *message)
{
  static const StreamingProtobufs__RRCReconfiguration init_value = STREAMING_PROTOBUFS__RRCRECONFIGURATION__INIT;
  *message = init_value;
}
size_t streaming_protobufs__rrcreconfiguration__get_packed_size
                     (const StreamingProtobufs__RRCReconfiguration *message)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t streaming_protobufs__rrcreconfiguration__pack
                     (const StreamingProtobufs__RRCReconfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t streaming_protobufs__rrcreconfiguration__pack_to_buffer
                     (const StreamingProtobufs__RRCReconfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StreamingProtobufs__RRCReconfiguration *
       streaming_protobufs__rrcreconfiguration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StreamingProtobufs__RRCReconfiguration *)
     protobuf_c_message_unpack (&streaming_protobufs__rrcreconfiguration__descriptor,
                                allocator, len, data);
}
void   streaming_protobufs__rrcreconfiguration__free_unpacked
                     (StreamingProtobufs__RRCReconfiguration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   streaming_protobufs__rrcreconfiguration__ies__init
                     (StreamingProtobufs__RRCReconfigurationIEs         *message)
{
  static const StreamingProtobufs__RRCReconfigurationIEs init_value = STREAMING_PROTOBUFS__RRCRECONFIGURATION__IES__INIT;
  *message = init_value;
}
size_t streaming_protobufs__rrcreconfiguration__ies__get_packed_size
                     (const StreamingProtobufs__RRCReconfigurationIEs *message)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t streaming_protobufs__rrcreconfiguration__ies__pack
                     (const StreamingProtobufs__RRCReconfigurationIEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t streaming_protobufs__rrcreconfiguration__ies__pack_to_buffer
                     (const StreamingProtobufs__RRCReconfigurationIEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StreamingProtobufs__RRCReconfigurationIEs *
       streaming_protobufs__rrcreconfiguration__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StreamingProtobufs__RRCReconfigurationIEs *)
     protobuf_c_message_unpack (&streaming_protobufs__rrcreconfiguration__ies__descriptor,
                                allocator, len, data);
}
void   streaming_protobufs__rrcreconfiguration__ies__free_unpacked
                     (StreamingProtobufs__RRCReconfigurationIEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration__ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   streaming_protobufs__rrcreconfiguration_v1530__ies__init
                     (StreamingProtobufs__RRCReconfigurationV1530IEs         *message)
{
  static const StreamingProtobufs__RRCReconfigurationV1530IEs init_value = STREAMING_PROTOBUFS__RRCRECONFIGURATION_V1530__IES__INIT;
  *message = init_value;
}
size_t streaming_protobufs__rrcreconfiguration_v1530__ies__get_packed_size
                     (const StreamingProtobufs__RRCReconfigurationV1530IEs *message)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t streaming_protobufs__rrcreconfiguration_v1530__ies__pack
                     (const StreamingProtobufs__RRCReconfigurationV1530IEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t streaming_protobufs__rrcreconfiguration_v1530__ies__pack_to_buffer
                     (const StreamingProtobufs__RRCReconfigurationV1530IEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StreamingProtobufs__RRCReconfigurationV1530IEs *
       streaming_protobufs__rrcreconfiguration_v1530__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StreamingProtobufs__RRCReconfigurationV1530IEs *)
     protobuf_c_message_unpack (&streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor,
                                allocator, len, data);
}
void   streaming_protobufs__rrcreconfiguration_v1530__ies__free_unpacked
                     (StreamingProtobufs__RRCReconfigurationV1530IEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   streaming_protobufs__master_key_update__init
                     (StreamingProtobufs__MasterKeyUpdate         *message)
{
  static const StreamingProtobufs__MasterKeyUpdate init_value = STREAMING_PROTOBUFS__MASTER_KEY_UPDATE__INIT;
  *message = init_value;
}
size_t streaming_protobufs__master_key_update__get_packed_size
                     (const StreamingProtobufs__MasterKeyUpdate *message)
{
  assert(message->base.descriptor == &streaming_protobufs__master_key_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t streaming_protobufs__master_key_update__pack
                     (const StreamingProtobufs__MasterKeyUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &streaming_protobufs__master_key_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t streaming_protobufs__master_key_update__pack_to_buffer
                     (const StreamingProtobufs__MasterKeyUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &streaming_protobufs__master_key_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StreamingProtobufs__MasterKeyUpdate *
       streaming_protobufs__master_key_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StreamingProtobufs__MasterKeyUpdate *)
     protobuf_c_message_unpack (&streaming_protobufs__master_key_update__descriptor,
                                allocator, len, data);
}
void   streaming_protobufs__master_key_update__free_unpacked
                     (StreamingProtobufs__MasterKeyUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &streaming_protobufs__master_key_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   streaming_protobufs__rrcreconfiguration_v1540__ies__init
                     (StreamingProtobufs__RRCReconfigurationV1540IEs         *message)
{
  static const StreamingProtobufs__RRCReconfigurationV1540IEs init_value = STREAMING_PROTOBUFS__RRCRECONFIGURATION_V1540__IES__INIT;
  *message = init_value;
}
size_t streaming_protobufs__rrcreconfiguration_v1540__ies__get_packed_size
                     (const StreamingProtobufs__RRCReconfigurationV1540IEs *message)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t streaming_protobufs__rrcreconfiguration_v1540__ies__pack
                     (const StreamingProtobufs__RRCReconfigurationV1540IEs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t streaming_protobufs__rrcreconfiguration_v1540__ies__pack_to_buffer
                     (const StreamingProtobufs__RRCReconfigurationV1540IEs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StreamingProtobufs__RRCReconfigurationV1540IEs *
       streaming_protobufs__rrcreconfiguration_v1540__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StreamingProtobufs__RRCReconfigurationV1540IEs *)
     protobuf_c_message_unpack (&streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor,
                                allocator, len, data);
}
void   streaming_protobufs__rrcreconfiguration_v1540__ies__free_unpacked
                     (StreamingProtobufs__RRCReconfigurationV1540IEs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor streaming_protobufs__rrcreconfiguration__field_descriptors[2] =
{
  {
    "rrc_TransactionIdentifier",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfiguration, rrc_transactionidentifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrcReconfiguration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StreamingProtobufs__RRCReconfiguration, critical_extensions_case),
    offsetof(StreamingProtobufs__RRCReconfiguration, rrcreconfiguration),
    &streaming_protobufs__rrcreconfiguration__ies__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned streaming_protobufs__rrcreconfiguration__field_indices_by_name[] = {
  1,   /* field[1] = rrcReconfiguration */
  0,   /* field[0] = rrc_TransactionIdentifier */
};
static const ProtobufCIntRange streaming_protobufs__rrcreconfiguration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor streaming_protobufs__rrcreconfiguration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "streaming_protobufs.RRCReconfiguration",
  "RRCReconfiguration",
  "StreamingProtobufs__RRCReconfiguration",
  "streaming_protobufs",
  sizeof(StreamingProtobufs__RRCReconfiguration),
  2,
  streaming_protobufs__rrcreconfiguration__field_descriptors,
  streaming_protobufs__rrcreconfiguration__field_indices_by_name,
  1,  streaming_protobufs__rrcreconfiguration__number_ranges,
  (ProtobufCMessageInit) streaming_protobufs__rrcreconfiguration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor streaming_protobufs__rrcreconfiguration__ies__field_descriptors[5] =
{
  {
    "radioBearerConfig",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationIEs, radiobearerconfig),
    &streaming_protobufs__radio_bearer_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "secondaryCellGroup",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationIEs, secondarycellgroup),
    &streaming_protobufs__cell_group_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "measConfig",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationIEs, measconfig),
    &streaming_protobufs__meas_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lateNonCriticalExtension",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationIEs, latenoncriticalextension),
    &google__protobuf__bytes_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonCriticalExtension",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationIEs, noncriticalextension),
    &streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned streaming_protobufs__rrcreconfiguration__ies__field_indices_by_name[] = {
  3,   /* field[3] = lateNonCriticalExtension */
  2,   /* field[2] = measConfig */
  4,   /* field[4] = nonCriticalExtension */
  0,   /* field[0] = radioBearerConfig */
  1,   /* field[1] = secondaryCellGroup */
};
static const ProtobufCIntRange streaming_protobufs__rrcreconfiguration__ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor streaming_protobufs__rrcreconfiguration__ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "streaming_protobufs.RRCReconfiguration_IEs",
  "RRCReconfigurationIEs",
  "StreamingProtobufs__RRCReconfigurationIEs",
  "streaming_protobufs",
  sizeof(StreamingProtobufs__RRCReconfigurationIEs),
  5,
  streaming_protobufs__rrcreconfiguration__ies__field_descriptors,
  streaming_protobufs__rrcreconfiguration__ies__field_indices_by_name,
  1,  streaming_protobufs__rrcreconfiguration__ies__number_ranges,
  (ProtobufCMessageInit) streaming_protobufs__rrcreconfiguration__ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor streaming_protobufs__rrcreconfiguration_v1530__ies__field_descriptors[8] =
{
  {
    "masterCellGroup",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, mastercellgroup),
    &streaming_protobufs__cell_group_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fullConfig",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, fullconfig),
    &streaming_protobufs__true_opt__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dedicatedNAS_MessageList",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, n_dedicatednas_messagelist),
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, dedicatednas_messagelist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "masterKeyUpdate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, masterkeyupdate),
    &streaming_protobufs__master_key_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dedicatedSIB1_Delivery",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, dedicatedsib1_delivery),
    &streaming_protobufs__sib1__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dedicatedSystemInformationDelivery",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, dedicatedsysteminformationdelivery),
    &streaming_protobufs__system_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "otherConfig",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, otherconfig),
    &streaming_protobufs__other_config__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonCriticalExtension",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1530IEs, noncriticalextension),
    &streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned streaming_protobufs__rrcreconfiguration_v1530__ies__field_indices_by_name[] = {
  2,   /* field[2] = dedicatedNAS_MessageList */
  4,   /* field[4] = dedicatedSIB1_Delivery */
  5,   /* field[5] = dedicatedSystemInformationDelivery */
  1,   /* field[1] = fullConfig */
  0,   /* field[0] = masterCellGroup */
  3,   /* field[3] = masterKeyUpdate */
  7,   /* field[7] = nonCriticalExtension */
  6,   /* field[6] = otherConfig */
};
static const ProtobufCIntRange streaming_protobufs__rrcreconfiguration_v1530__ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor streaming_protobufs__rrcreconfiguration_v1530__ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "streaming_protobufs.RRCReconfiguration_v1530_IEs",
  "RRCReconfigurationV1530IEs",
  "StreamingProtobufs__RRCReconfigurationV1530IEs",
  "streaming_protobufs",
  sizeof(StreamingProtobufs__RRCReconfigurationV1530IEs),
  8,
  streaming_protobufs__rrcreconfiguration_v1530__ies__field_descriptors,
  streaming_protobufs__rrcreconfiguration_v1530__ies__field_indices_by_name,
  1,  streaming_protobufs__rrcreconfiguration_v1530__ies__number_ranges,
  (ProtobufCMessageInit) streaming_protobufs__rrcreconfiguration_v1530__ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor streaming_protobufs__master_key_update__field_descriptors[3] =
{
  {
    "keySetChangeIndicator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__MasterKeyUpdate, keysetchangeindicator),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nextHopChainingCount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__MasterKeyUpdate, nexthopchainingcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nas_Container",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__MasterKeyUpdate, nas_container),
    &google__protobuf__bytes_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned streaming_protobufs__master_key_update__field_indices_by_name[] = {
  0,   /* field[0] = keySetChangeIndicator */
  2,   /* field[2] = nas_Container */
  1,   /* field[1] = nextHopChainingCount */
};
static const ProtobufCIntRange streaming_protobufs__master_key_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor streaming_protobufs__master_key_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "streaming_protobufs.MasterKeyUpdate",
  "MasterKeyUpdate",
  "StreamingProtobufs__MasterKeyUpdate",
  "streaming_protobufs",
  sizeof(StreamingProtobufs__MasterKeyUpdate),
  3,
  streaming_protobufs__master_key_update__field_descriptors,
  streaming_protobufs__master_key_update__field_indices_by_name,
  1,  streaming_protobufs__master_key_update__number_ranges,
  (ProtobufCMessageInit) streaming_protobufs__master_key_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor streaming_protobufs__rrcreconfiguration_v1540__ies__field_descriptors[1] =
{
  {
    "otherConfig_v1540",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(StreamingProtobufs__RRCReconfigurationV1540IEs, otherconfig_v1540),
    &streaming_protobufs__other_config_v1540__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned streaming_protobufs__rrcreconfiguration_v1540__ies__field_indices_by_name[] = {
  0,   /* field[0] = otherConfig_v1540 */
};
static const ProtobufCIntRange streaming_protobufs__rrcreconfiguration_v1540__ies__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor streaming_protobufs__rrcreconfiguration_v1540__ies__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "streaming_protobufs.RRCReconfiguration_v1540_IEs",
  "RRCReconfigurationV1540IEs",
  "StreamingProtobufs__RRCReconfigurationV1540IEs",
  "streaming_protobufs",
  sizeof(StreamingProtobufs__RRCReconfigurationV1540IEs),
  1,
  streaming_protobufs__rrcreconfiguration_v1540__ies__field_descriptors,
  streaming_protobufs__rrcreconfiguration_v1540__ies__field_indices_by_name,
  1,  streaming_protobufs__rrcreconfiguration_v1540__ies__number_ranges,
  (ProtobufCMessageInit) streaming_protobufs__rrcreconfiguration_v1540__ies__init,
  NULL,NULL,NULL    /* reserved[123] */
};
