/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_modification_required.proto */

#ifndef PROTOBUF_C_sgnb_5fmodification_5frequired_2eproto__INCLUDED
#define PROTOBUF_C_sgnb_5fmodification_5frequired_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "common_types.pb-c.h"
#include "x2ap_common_types.pb-c.h"
#include "rrc_cg_config.pb-c.h"
#include "error_cause.pb-c.h"

typedef struct _StreamingProtobufs__SgNBModificationRequired StreamingProtobufs__SgNBModificationRequired;
typedef struct _StreamingProtobufs__SgNBModificationRequiredIEs StreamingProtobufs__SgNBModificationRequiredIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs;


/* --- enums --- */


/* --- messages --- */

struct  _StreamingProtobufs__SgNBModificationRequired
{
  ProtobufCMessage base;
  StreamingProtobufs__SgNBModificationRequiredIEs *protocolies;
};
#define STREAMING_PROTOBUFS__SG_NBMODIFICATION_REQUIRED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbmodification_required__descriptor) \
    , NULL }


struct  _StreamingProtobufs__SgNBModificationRequiredIEs
{
  ProtobufCMessage base;
  uint32_t id_menb_ue_x2ap_id;
  uint32_t id_sgnb_ue_x2ap_id;
  StreamingProtobufs__Cause *id_cause;
  StreamingProtobufs__PDCPChangeIndication *id_pdcpchangeindication;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList *id_e_rabs_tobereleased_sgnbmodreqdlist;
  /*
   *The content of id_SgNBtoMeNBContainer has been specified in 3GPP 38.331 to be CG-Config.
   */
  StreamingProtobufs__CGConfig *id_sgnbtomenbcontainer;
  Google__Protobuf__UInt32Value *id_menb_ue_x2ap_id_extension;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList *id_e_rabs_tobemodified_sgnbmodreqdlist;
  StreamingProtobufs__SgNBResourceCoordinationInformation *id_sgnbresourcecoordinationinformation;
  StreamingProtobufs__RRCConfigInd *id_rrcconfigindication;
};
#define STREAMING_PROTOBUFS__SG_NBMODIFICATION_REQUIRED__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbmodification_required__ies__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList
{
  ProtobufCMessage base;
  size_t n_items;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs **items;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQD_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem *id_e_rabs_tobereleased_sgnbmodreqd_item;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQD__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__descriptor) \
    , NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  StreamingProtobufs__Cause *cause;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQD__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__descriptor) \
    , 0, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__RLCMode *id_rlcmode_transferred;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQD__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__descriptor) \
    , NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList
{
  ProtobufCMessage base;
  size_t n_items;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs **items;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem *id_e_rabs_tobemodified_sgnbmodreqd_item;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__descriptor) \
    , NULL }


typedef enum {
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 3,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__RESOURCE_CONFIGURATION)
} StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem__ResourceConfigurationCase;

struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  StreamingProtobufs__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs **ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem__ResourceConfigurationCase resource_configuration_case;
  union {
    StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent *sgnbpdcppresent;
    StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__descriptor) \
    , 0, NULL, 0,NULL, STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__descriptor) \
     }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABLevelQoSParameters *requested_mcg_e_rab_level_qos_parameters;
  StreamingProtobufs__ULConfiguration *ul_configuration;
  StreamingProtobufs__GTPtunnelEndpoint *sgnb_ul_gtp_teidatpdcp;
  StreamingProtobufs__GTPtunnelEndpoint *s1_dl_gtp_teidatsgnb;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__PDCPSnLength *id_ulpdcpsnlength;
  StreamingProtobufs__PDCPSnLength *id_dlpdcpsnlength;
  StreamingProtobufs__TrueOpt *id_new_drb_id_req;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__descriptor) \
    , NULL, NULL, NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__GTPtunnelEndpoint *sgnb_dl_gtp_teidatscg;
  StreamingProtobufs__GTPtunnelEndpoint *secondary_sgnb_dl_gtp_teidatscg;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__RLCStatus *id_rlc_status;
  Google__Protobuf__UInt32Value *id_lcid;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQD__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__descriptor) \
    , NULL, NULL }


/* StreamingProtobufs__SgNBModificationRequired methods */
void   streaming_protobufs__sg_nbmodification_required__init
                     (StreamingProtobufs__SgNBModificationRequired         *message);
size_t streaming_protobufs__sg_nbmodification_required__get_packed_size
                     (const StreamingProtobufs__SgNBModificationRequired   *message);
size_t streaming_protobufs__sg_nbmodification_required__pack
                     (const StreamingProtobufs__SgNBModificationRequired   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbmodification_required__pack_to_buffer
                     (const StreamingProtobufs__SgNBModificationRequired   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBModificationRequired *
       streaming_protobufs__sg_nbmodification_required__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbmodification_required__free_unpacked
                     (StreamingProtobufs__SgNBModificationRequired *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__SgNBModificationRequiredIEs methods */
void   streaming_protobufs__sg_nbmodification_required__ies__init
                     (StreamingProtobufs__SgNBModificationRequiredIEs         *message);
size_t streaming_protobufs__sg_nbmodification_required__ies__get_packed_size
                     (const StreamingProtobufs__SgNBModificationRequiredIEs   *message);
size_t streaming_protobufs__sg_nbmodification_required__ies__pack
                     (const StreamingProtobufs__SgNBModificationRequiredIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbmodification_required__ies__pack_to_buffer
                     (const StreamingProtobufs__SgNBModificationRequiredIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBModificationRequiredIEs *
       streaming_protobufs__sg_nbmodification_required__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbmodification_required__ies__free_unpacked
                     (StreamingProtobufs__SgNBModificationRequiredIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StreamingProtobufs__SgNBModificationRequired_Closure)
                 (const StreamingProtobufs__SgNBModificationRequired *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__SgNBModificationRequiredIEs_Closure)
                 (const StreamingProtobufs__SgNBModificationRequiredIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdList *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItem *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqdItemExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdList *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItem *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdItemExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqdSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbmodification_required__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbmodification_required__ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd_list__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_reqd__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd_list__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_reqd__sg_nbpdcpnotpresent_ext_ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sgnb_5fmodification_5frequired_2eproto__INCLUDED */
