/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: x2ap_streaming.proto */

#ifndef PROTOBUF_C_x2ap_5fstreaming_2eproto__INCLUDED
#define PROTOBUF_C_x2ap_5fstreaming_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "rrctransfer.pb-c.h"
#include "sgnb_addition_request.pb-c.h"
#include "sgnb_addition_request_acknowledge.pb-c.h"
#include "sgnb_addition_request_reject.pb-c.h"
#include "sgnb_modification_request.pb-c.h"
#include "sgnb_modification_request_acknowledge.pb-c.h"
#include "sgnb_modification_request_reject.pb-c.h"
#include "sgnb_modification_required.pb-c.h"
#include "sgnb_modification_confirm.pb-c.h"
#include "sgnb_modification_refuse.pb-c.h"
#include "sgnb_release_request.pb-c.h"
#include "sgnb_release_request_acknowledge.pb-c.h"
#include "sgnb_release_required.pb-c.h"
#include "sgnb_release_confirm.pb-c.h"
#include "sgnb_reconfiguration_complete.pb-c.h"
#include "sn_status_transfer.pb-c.h"
#include "ue_context_release.pb-c.h"
#include "secondary_rat_data_usage_report.pb-c.h"
#include "sgnb_change_required.pb-c.h"
#include "sgnb_change_confirm.pb-c.h"
#include "sgnb_change_refuse.pb-c.h"
#include "sgnb_activity_notification.pb-c.h"
#include "gnb_status_indication.pb-c.h"

typedef struct _StreamingProtobufs__X2APStreaming StreamingProtobufs__X2APStreaming;
typedef struct _StreamingProtobufs__X2APStreamingHeader StreamingProtobufs__X2APStreamingHeader;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE__NOT_SET = 0,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_RRC_TRANSFER = 2,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBADDITION_REQUEST = 3,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBADDITION_REQUEST_ACKNOWLEDGE = 4,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBADDITION_REQUEST_REJECT = 5,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_REQUEST = 6,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_REQUEST_ACKNOWLEDGE = 7,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_REQUEST_REJECT = 8,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_REQUIRED = 9,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_CONFIRM = 10,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBMODIFICATION_REFUSE = 11,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBRECONFIGURATION_COMPLETE = 12,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NB_RELEASE_REQUEST = 13,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NB_RELEASE_REQUEST_ACKNOWLEDGE = 14,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NB_RELEASE_REQUIRED = 15,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NB_RELEASE_CONFIRM = 16,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SN_STATUS_TRANSFER = 17,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_UE_CONTEXT_RELEASE = 18,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SECONDARY_RATDATA_USAGE_REPORT = 19,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBCHANGE_REQUIRED = 20,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBCHANGE_CONFIRM = 21,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBCHANGE_REFUSE = 22,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_SG_NBACTIVITY_NOTIFICATION = 23,
  STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE_G_NBSTATUS_INDICATION = 24
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE)
} StreamingProtobufs__X2APStreaming__X2apMessageCase;

struct  _StreamingProtobufs__X2APStreaming
{
  ProtobufCMessage base;
  StreamingProtobufs__X2APStreamingHeader *header;
  StreamingProtobufs__X2APStreaming__X2apMessageCase x2ap_message_case;
  union {
    StreamingProtobufs__RRCTransfer *rrctransfer;
    StreamingProtobufs__SgNBAdditionRequest *sgnbadditionrequest;
    StreamingProtobufs__SgNBAdditionRequestAcknowledge *sgnbadditionrequestacknowledge;
    StreamingProtobufs__SgNBAdditionRequestReject *sgnbadditionrequestreject;
    StreamingProtobufs__SgNBModificationRequest *sgnbmodificationrequest;
    StreamingProtobufs__SgNBModificationRequestAcknowledge *sgnbmodificationrequestacknowledge;
    StreamingProtobufs__SgNBModificationRequestReject *sgnbmodificationrequestreject;
    StreamingProtobufs__SgNBModificationRequired *sgnbmodificationrequired;
    StreamingProtobufs__SgNBModificationConfirm *sgnbmodificationconfirm;
    StreamingProtobufs__SgNBModificationRefuse *sgnbmodificationrefuse;
    StreamingProtobufs__SgNBReconfigurationComplete *sgnbreconfigurationcomplete;
    StreamingProtobufs__SgNBReleaseRequest *sgnbreleaserequest;
    StreamingProtobufs__SgNBReleaseRequestAcknowledge *sgnbreleaserequestacknowledge;
    StreamingProtobufs__SgNBReleaseRequired *sgnbreleaserequired;
    StreamingProtobufs__SgNBReleaseConfirm *sgnbreleaseconfirm;
    StreamingProtobufs__SNStatusTransfer *snstatustransfer;
    StreamingProtobufs__UEContextRelease *uecontextrelease;
    StreamingProtobufs__SecondaryRATDataUsageReport *secondaryratdatausagereport;
    StreamingProtobufs__SgNBChangeRequired *sgnbchangerequired;
    StreamingProtobufs__SgNBChangeConfirm *sgnbchangeconfirm;
    StreamingProtobufs__SgNBChangeRefuse *sgnbchangerefuse;
    StreamingProtobufs__SgNBActivityNotification *sgnbactivitynotification;
    StreamingProtobufs__GNBStatusIndication *gnbstatusindication;
  };
};
#define STREAMING_PROTOBUFS__X2_APSTREAMING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__x2_apstreaming__descriptor) \
    , NULL, STREAMING_PROTOBUFS__X2_APSTREAMING__X2AP_MESSAGE__NOT_SET, {0} }


struct  _StreamingProtobufs__X2APStreamingHeader
{
  ProtobufCMessage base;
  /*
   *The revision number of X2AP streaming protobuf files
   */
  char *protobuf_revision;
  /*
   *Identifier of gNodeB
   */
  Google__Protobuf__StringValue *gnbid;
  /*
   *The timestamp of RIC INDICATION header, which contains 64-bit
   *timestamp value as defined in section 6 of IETF RFC 5905.
   */
  uint64_t timestamp;
};
#define STREAMING_PROTOBUFS__X2_APSTREAMING_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__x2_apstreaming_header__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, 0 }


/* StreamingProtobufs__X2APStreaming methods */
void   streaming_protobufs__x2_apstreaming__init
                     (StreamingProtobufs__X2APStreaming         *message);
size_t streaming_protobufs__x2_apstreaming__get_packed_size
                     (const StreamingProtobufs__X2APStreaming   *message);
size_t streaming_protobufs__x2_apstreaming__pack
                     (const StreamingProtobufs__X2APStreaming   *message,
                      uint8_t             *out);
size_t streaming_protobufs__x2_apstreaming__pack_to_buffer
                     (const StreamingProtobufs__X2APStreaming   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__X2APStreaming *
       streaming_protobufs__x2_apstreaming__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__x2_apstreaming__free_unpacked
                     (StreamingProtobufs__X2APStreaming *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__X2APStreamingHeader methods */
void   streaming_protobufs__x2_apstreaming_header__init
                     (StreamingProtobufs__X2APStreamingHeader         *message);
size_t streaming_protobufs__x2_apstreaming_header__get_packed_size
                     (const StreamingProtobufs__X2APStreamingHeader   *message);
size_t streaming_protobufs__x2_apstreaming_header__pack
                     (const StreamingProtobufs__X2APStreamingHeader   *message,
                      uint8_t             *out);
size_t streaming_protobufs__x2_apstreaming_header__pack_to_buffer
                     (const StreamingProtobufs__X2APStreamingHeader   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__X2APStreamingHeader *
       streaming_protobufs__x2_apstreaming_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__x2_apstreaming_header__free_unpacked
                     (StreamingProtobufs__X2APStreamingHeader *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StreamingProtobufs__X2APStreaming_Closure)
                 (const StreamingProtobufs__X2APStreaming *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__X2APStreamingHeader_Closure)
                 (const StreamingProtobufs__X2APStreamingHeader *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor streaming_protobufs__x2_apstreaming__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__x2_apstreaming_header__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_x2ap_5fstreaming_2eproto__INCLUDED */
