apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-env
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: <certificate>
        server: https://<kube-ip>:<kube-port>
      name: <name>
    contexts:
    - context:
        cluster:<cluster-name>
        user: <user>
      name: <name>
    current-context: <context>
    kind: Config
    preferences: {}
    users:
    - name: <name>
      user:
        client-certificate-data: <cliet-cert> 
        client-key-data: <client-key-data>