---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ricdeploy.ricplt.com
  resources:
  - ricplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ricdeploy.ricplt.com
  resources:
  - ricplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - ricdeploy.ricplt.com
  resources:
  - ricplatforms/status
  verbs:
  - get
  - patch
  - update
