apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "e2adapter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "e2adapter.name" . }}
    helm.sh/chart: {{ include "e2adapter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "e2adapter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "e2adapter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /etc/e2adapter/e2adapter.conf
            name: local-configuration-file
            subPath: e2adapter.conf
      volumes:
        - name: local-configuration-file
          configMap:
            name: e2adapter-configuration-configmap

