// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rrc_system_information.proto

package streaming_protobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SystemInformation struct {
	// Types that are valid to be assigned to CriticalExtensions:
	//	*SystemInformation_SystemInformationR15
	CriticalExtensions   isSystemInformation_CriticalExtensions `protobuf_oneof:"criticalExtensions"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *SystemInformation) Reset()         { *m = SystemInformation{} }
func (m *SystemInformation) String() string { return proto.CompactTextString(m) }
func (*SystemInformation) ProtoMessage()    {}
func (*SystemInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5125919ffcc3a355, []int{0}
}

func (m *SystemInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInformation.Unmarshal(m, b)
}
func (m *SystemInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInformation.Marshal(b, m, deterministic)
}
func (m *SystemInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInformation.Merge(m, src)
}
func (m *SystemInformation) XXX_Size() int {
	return xxx_messageInfo_SystemInformation.Size(m)
}
func (m *SystemInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInformation.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInformation proto.InternalMessageInfo

type isSystemInformation_CriticalExtensions interface {
	isSystemInformation_CriticalExtensions()
}

type SystemInformation_SystemInformationR15 struct {
	SystemInformationR15 *SystemInformation_IEs `protobuf:"bytes,1,opt,name=systemInformation_r15,json=systemInformationR15,proto3,oneof"`
}

func (*SystemInformation_SystemInformationR15) isSystemInformation_CriticalExtensions() {}

func (m *SystemInformation) GetCriticalExtensions() isSystemInformation_CriticalExtensions {
	if m != nil {
		return m.CriticalExtensions
	}
	return nil
}

func (m *SystemInformation) GetSystemInformationR15() *SystemInformation_IEs {
	if x, ok := m.GetCriticalExtensions().(*SystemInformation_SystemInformationR15); ok {
		return x.SystemInformationR15
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SystemInformation) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SystemInformation_SystemInformationR15)(nil),
	}
}

type SystemInformation_IEs struct {
	Sib_TypeAndInfo          []*SIB_TypeAndInfo   `protobuf:"bytes,1,rep,name=sib_TypeAndInfo,json=sibTypeAndInfo,proto3" json:"sib_TypeAndInfo,omitempty"`
	LateNonCriticalExtension *wrappers.BytesValue `protobuf:"bytes,2,opt,name=lateNonCriticalExtension,proto3" json:"lateNonCriticalExtension,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}             `json:"-"`
	XXX_unrecognized         []byte               `json:"-"`
	XXX_sizecache            int32                `json:"-"`
}

func (m *SystemInformation_IEs) Reset()         { *m = SystemInformation_IEs{} }
func (m *SystemInformation_IEs) String() string { return proto.CompactTextString(m) }
func (*SystemInformation_IEs) ProtoMessage()    {}
func (*SystemInformation_IEs) Descriptor() ([]byte, []int) {
	return fileDescriptor_5125919ffcc3a355, []int{1}
}

func (m *SystemInformation_IEs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInformation_IEs.Unmarshal(m, b)
}
func (m *SystemInformation_IEs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInformation_IEs.Marshal(b, m, deterministic)
}
func (m *SystemInformation_IEs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInformation_IEs.Merge(m, src)
}
func (m *SystemInformation_IEs) XXX_Size() int {
	return xxx_messageInfo_SystemInformation_IEs.Size(m)
}
func (m *SystemInformation_IEs) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInformation_IEs.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInformation_IEs proto.InternalMessageInfo

func (m *SystemInformation_IEs) GetSib_TypeAndInfo() []*SIB_TypeAndInfo {
	if m != nil {
		return m.Sib_TypeAndInfo
	}
	return nil
}

func (m *SystemInformation_IEs) GetLateNonCriticalExtension() *wrappers.BytesValue {
	if m != nil {
		return m.LateNonCriticalExtension
	}
	return nil
}

type SIB_TypeAndInfo struct {
	// Types that are valid to be assigned to C:
	//	*SIB_TypeAndInfo_Sib2
	//	*SIB_TypeAndInfo_Sib3
	//	*SIB_TypeAndInfo_Sib4
	//	*SIB_TypeAndInfo_Sib5
	//	*SIB_TypeAndInfo_Sib6
	//	*SIB_TypeAndInfo_Sib7
	//	*SIB_TypeAndInfo_Sib8
	//	*SIB_TypeAndInfo_Sib9
	C                    isSIB_TypeAndInfo_C `protobuf_oneof:"c"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SIB_TypeAndInfo) Reset()         { *m = SIB_TypeAndInfo{} }
func (m *SIB_TypeAndInfo) String() string { return proto.CompactTextString(m) }
func (*SIB_TypeAndInfo) ProtoMessage()    {}
func (*SIB_TypeAndInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5125919ffcc3a355, []int{2}
}

func (m *SIB_TypeAndInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIB_TypeAndInfo.Unmarshal(m, b)
}
func (m *SIB_TypeAndInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIB_TypeAndInfo.Marshal(b, m, deterministic)
}
func (m *SIB_TypeAndInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIB_TypeAndInfo.Merge(m, src)
}
func (m *SIB_TypeAndInfo) XXX_Size() int {
	return xxx_messageInfo_SIB_TypeAndInfo.Size(m)
}
func (m *SIB_TypeAndInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SIB_TypeAndInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SIB_TypeAndInfo proto.InternalMessageInfo

type isSIB_TypeAndInfo_C interface {
	isSIB_TypeAndInfo_C()
}

type SIB_TypeAndInfo_Sib2 struct {
	Sib2 *SIB2 `protobuf:"bytes,1,opt,name=sib2,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib3 struct {
	Sib3 *SIB3 `protobuf:"bytes,2,opt,name=sib3,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib4 struct {
	Sib4 *SIB4 `protobuf:"bytes,3,opt,name=sib4,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib5 struct {
	Sib5 *SIB5 `protobuf:"bytes,4,opt,name=sib5,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib6 struct {
	Sib6 *SIB6 `protobuf:"bytes,5,opt,name=sib6,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib7 struct {
	Sib7 *SIB7 `protobuf:"bytes,6,opt,name=sib7,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib8 struct {
	Sib8 *SIB8 `protobuf:"bytes,7,opt,name=sib8,proto3,oneof"`
}

type SIB_TypeAndInfo_Sib9 struct {
	Sib9 *SIB9 `protobuf:"bytes,8,opt,name=sib9,proto3,oneof"`
}

func (*SIB_TypeAndInfo_Sib2) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib3) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib4) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib5) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib6) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib7) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib8) isSIB_TypeAndInfo_C() {}

func (*SIB_TypeAndInfo_Sib9) isSIB_TypeAndInfo_C() {}

func (m *SIB_TypeAndInfo) GetC() isSIB_TypeAndInfo_C {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib2() *SIB2 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib2); ok {
		return x.Sib2
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib3() *SIB3 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib3); ok {
		return x.Sib3
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib4() *SIB4 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib4); ok {
		return x.Sib4
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib5() *SIB5 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib5); ok {
		return x.Sib5
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib6() *SIB6 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib6); ok {
		return x.Sib6
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib7() *SIB7 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib7); ok {
		return x.Sib7
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib8() *SIB8 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib8); ok {
		return x.Sib8
	}
	return nil
}

func (m *SIB_TypeAndInfo) GetSib9() *SIB9 {
	if x, ok := m.GetC().(*SIB_TypeAndInfo_Sib9); ok {
		return x.Sib9
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SIB_TypeAndInfo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SIB_TypeAndInfo_Sib2)(nil),
		(*SIB_TypeAndInfo_Sib3)(nil),
		(*SIB_TypeAndInfo_Sib4)(nil),
		(*SIB_TypeAndInfo_Sib5)(nil),
		(*SIB_TypeAndInfo_Sib6)(nil),
		(*SIB_TypeAndInfo_Sib7)(nil),
		(*SIB_TypeAndInfo_Sib8)(nil),
		(*SIB_TypeAndInfo_Sib9)(nil),
	}
}

func init() {
	proto.RegisterType((*SystemInformation)(nil), "streaming_protobufs.SystemInformation")
	proto.RegisterType((*SystemInformation_IEs)(nil), "streaming_protobufs.SystemInformation_IEs")
	proto.RegisterType((*SIB_TypeAndInfo)(nil), "streaming_protobufs.SIB_TypeAndInfo")
}

func init() { proto.RegisterFile("rrc_system_information.proto", fileDescriptor_5125919ffcc3a355) }

var fileDescriptor_5125919ffcc3a355 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd0, 0x5d, 0xab, 0xd3, 0x30,
	0x18, 0x07, 0xf0, 0x53, 0x7b, 0x3c, 0x4a, 0x0e, 0x7a, 0xb0, 0x9e, 0x49, 0x9c, 0x22, 0x63, 0x78,
	0x31, 0x84, 0xa6, 0xac, 0x5d, 0xf7, 0x72, 0x69, 0x65, 0xb0, 0x5d, 0xe8, 0x45, 0x15, 0x05, 0x6f,
	0x4a, 0x5a, 0xb3, 0x12, 0x68, 0x93, 0x92, 0x64, 0x68, 0xbf, 0x83, 0x9f, 0xc1, 0xaf, 0xe2, 0x57,
	0x93, 0x75, 0xcf, 0xe6, 0xd8, 0x4b, 0xef, 0x96, 0x67, 0xf9, 0xfd, 0x9f, 0x7f, 0x83, 0x5e, 0x2b,
	0x95, 0x25, 0xba, 0xd6, 0x86, 0x95, 0x09, 0x17, 0x2b, 0xa9, 0x4a, 0x6a, 0xb8, 0x14, 0xa4, 0x52,
	0xd2, 0x48, 0xe7, 0xb9, 0x36, 0x8a, 0xd1, 0x92, 0x8b, 0x3c, 0x69, 0x06, 0xe9, 0x7a, 0xa5, 0xbb,
	0x6f, 0x72, 0x29, 0xf3, 0x82, 0x79, 0xbb, 0x89, 0xf7, 0x53, 0xd1, 0xaa, 0x62, 0x4a, 0x6f, 0x51,
	0xf7, 0xc5, 0x26, 0x32, 0x93, 0x65, 0x29, 0x45, 0x62, 0xea, 0x8a, 0xed, 0xe6, 0x4f, 0x9a, 0x55,
	0x3c, 0xdd, 0x1e, 0xfb, 0xbf, 0x2d, 0xf4, 0xec, 0x73, 0xb3, 0x78, 0xf9, 0x7f, 0xaf, 0x43, 0x51,
	0x47, 0x1f, 0x0f, 0x13, 0x35, 0x0c, 0xb1, 0xd5, 0xb3, 0x06, 0xb7, 0xfe, 0x3b, 0x72, 0xa6, 0x11,
	0x39, 0x89, 0x49, 0x96, 0x73, 0xbd, 0xb8, 0x8a, 0xef, 0x4f, 0xa2, 0xe2, 0x61, 0x18, 0xdd, 0x23,
	0x27, 0x53, 0xdc, 0xf0, 0x8c, 0x16, 0xf3, 0x5f, 0x86, 0x09, 0xcd, 0xa5, 0xd0, 0xfd, 0xbf, 0x16,
	0xea, 0x9c, 0xcd, 0x71, 0x3e, 0xa2, 0x3b, 0xcd, 0xd3, 0xe4, 0x4b, 0x5d, 0xb1, 0xf7, 0xe2, 0xc7,
	0xe6, 0x5f, 0x6c, 0xf5, 0xec, 0xc1, 0xad, 0xff, 0xf6, 0x7c, 0x99, 0x65, 0x74, 0x78, 0x37, 0x7e,
	0xaa, 0x79, 0x7a, 0x70, 0x76, 0xbe, 0x21, 0x5c, 0x50, 0xc3, 0x3e, 0x49, 0xf1, 0xe1, 0xb8, 0x05,
	0x7e, 0xd0, 0x7c, 0xe4, 0x2b, 0xb2, 0x7d, 0x61, 0xb2, 0x0b, 0x25, 0x51, 0x6d, 0x98, 0xfe, 0x4a,
	0x8b, 0x35, 0x8b, 0x2f, 0xe2, 0xfe, 0x1f, 0x1b, 0xdd, 0x1d, 0x2d, 0x77, 0x3c, 0x74, 0xad, 0x79,
	0xea, 0xc3, 0xeb, 0xbd, 0xbc, 0x54, 0xd8, 0x5f, 0x5c, 0xc5, 0xcd, 0x45, 0x00, 0x01, 0x34, 0xb9,
	0x08, 0x02, 0x00, 0x01, 0x80, 0x11, 0xb6, 0xdb, 0xc1, 0x08, 0xc0, 0x08, 0x40, 0x88, 0xaf, 0xdb,
	0x41, 0x08, 0x20, 0x04, 0x30, 0xc6, 0x0f, 0xdb, 0xc1, 0x18, 0xc0, 0x18, 0xc0, 0x04, 0xdf, 0xb4,
	0x83, 0x09, 0x80, 0x09, 0x80, 0x29, 0x7e, 0xd4, 0x0e, 0xa6, 0x00, 0xa6, 0x00, 0x66, 0xf8, 0x71,
	0x3b, 0x98, 0x01, 0x98, 0x45, 0x36, 0xb2, 0xb2, 0x28, 0xf8, 0x3e, 0xcc, 0x99, 0x52, 0xdc, 0x10,
	0xe9, 0x2a, 0x2a, 0x5c, 0x9d, 0x11, 0xa9, 0x72, 0x4f, 0x79, 0x8a, 0x67, 0x6e, 0x55, 0x18, 0x6f,
	0x1f, 0xe3, 0xee, 0x63, 0xd2, 0x9b, 0xe6, 0x67, 0xf0, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xba, 0x34,
	0xa5, 0x64, 0xa9, 0x03, 0x00, 0x00,
}
