// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sgnb_addition_request_acknowledge.proto

package streaming_protobufs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SgNBAdditionRequestAcknowledge struct {
	Id_MeNB_UE_X2AP_ID                             uint32                                       `protobuf:"varint,1,opt,name=id_MeNB_UE_X2AP_ID,json=idMeNBUEX2APID,proto3" json:"id_MeNB_UE_X2AP_ID,omitempty"`
	Id_SgNB_UE_X2AP_ID                             uint32                                       `protobuf:"varint,2,opt,name=id_SgNB_UE_X2AP_ID,json=idSgNBUEX2APID,proto3" json:"id_SgNB_UE_X2AP_ID,omitempty"`
	Id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList `protobuf:"bytes,3,opt,name=id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList,json=idERABsAdmittedToBeAddedSgNBAddReqAckList,proto3" json:"id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList,omitempty"`
	Id_E_RABs_NotAdmitted_List                     *E_RAB_List                                  `protobuf:"bytes,4,opt,name=id_E_RABs_NotAdmitted_List,json=idERABsNotAdmittedList,proto3" json:"id_E_RABs_NotAdmitted_List,omitempty"`
	//The content of id_SgNBtoMeNBContainer has been specified in 3GPP 38.331 to be CG-Config.
	Id_SgNBtoMeNBContainer                 *CG_Config                           `protobuf:"bytes,5,opt,name=id_SgNBtoMeNBContainer,json=idSgNBtoMeNBContainer,proto3" json:"id_SgNBtoMeNBContainer,omitempty"`
	Id_CriticalityDiagnostics              *CriticalityDiagnostics              `protobuf:"bytes,6,opt,name=id_CriticalityDiagnostics,json=idCriticalityDiagnostics,proto3" json:"id_CriticalityDiagnostics,omitempty"`
	Id_MeNB_UE_X2AP_ID_Extension           *wrappers.UInt32Value                `protobuf:"bytes,7,opt,name=id_MeNB_UE_X2AP_ID_Extension,json=idMeNBUEX2APIDExtension,proto3" json:"id_MeNB_UE_X2AP_ID_Extension,omitempty"`
	Id_AdmittedSplitSRBs                   *SplitSRBs                           `protobuf:"bytes,8,opt,name=id_AdmittedSplitSRBs,json=idAdmittedSplitSRBs,proto3" json:"id_AdmittedSplitSRBs,omitempty"`
	Id_SgNBResourceCoordinationInformation *SgNBResourceCoordinationInformation `protobuf:"bytes,9,opt,name=id_SgNBResourceCoordinationInformation,json=idSgNBResourceCoordinationInformation,proto3" json:"id_SgNBResourceCoordinationInformation,omitempty"`
	Id_RRCConfigIndication                 *RRC_Config_Ind                      `protobuf:"bytes,10,opt,name=id_RRCConfigIndication,json=idRRCConfigIndication,proto3" json:"id_RRCConfigIndication,omitempty"`
	XXX_NoUnkeyedLiteral                   struct{}                             `json:"-"`
	XXX_unrecognized                       []byte                               `json:"-"`
	XXX_sizecache                          int32                                `json:"-"`
}

func (m *SgNBAdditionRequestAcknowledge) Reset()         { *m = SgNBAdditionRequestAcknowledge{} }
func (m *SgNBAdditionRequestAcknowledge) String() string { return proto.CompactTextString(m) }
func (*SgNBAdditionRequestAcknowledge) ProtoMessage()    {}
func (*SgNBAdditionRequestAcknowledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{0}
}

func (m *SgNBAdditionRequestAcknowledge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SgNBAdditionRequestAcknowledge.Unmarshal(m, b)
}
func (m *SgNBAdditionRequestAcknowledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SgNBAdditionRequestAcknowledge.Marshal(b, m, deterministic)
}
func (m *SgNBAdditionRequestAcknowledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SgNBAdditionRequestAcknowledge.Merge(m, src)
}
func (m *SgNBAdditionRequestAcknowledge) XXX_Size() int {
	return xxx_messageInfo_SgNBAdditionRequestAcknowledge.Size(m)
}
func (m *SgNBAdditionRequestAcknowledge) XXX_DiscardUnknown() {
	xxx_messageInfo_SgNBAdditionRequestAcknowledge.DiscardUnknown(m)
}

var xxx_messageInfo_SgNBAdditionRequestAcknowledge proto.InternalMessageInfo

func (m *SgNBAdditionRequestAcknowledge) GetId_MeNB_UE_X2AP_ID() uint32 {
	if m != nil {
		return m.Id_MeNB_UE_X2AP_ID
	}
	return 0
}

func (m *SgNBAdditionRequestAcknowledge) GetId_SgNB_UE_X2AP_ID() uint32 {
	if m != nil {
		return m.Id_SgNB_UE_X2AP_ID
	}
	return 0
}

func (m *SgNBAdditionRequestAcknowledge) GetId_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList() *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList {
	if m != nil {
		return m.Id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_E_RABs_NotAdmitted_List() *E_RAB_List {
	if m != nil {
		return m.Id_E_RABs_NotAdmitted_List
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_SgNBtoMeNBContainer() *CG_Config {
	if m != nil {
		return m.Id_SgNBtoMeNBContainer
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_CriticalityDiagnostics() *CriticalityDiagnostics {
	if m != nil {
		return m.Id_CriticalityDiagnostics
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_MeNB_UE_X2AP_ID_Extension() *wrappers.UInt32Value {
	if m != nil {
		return m.Id_MeNB_UE_X2AP_ID_Extension
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_AdmittedSplitSRBs() *SplitSRBs {
	if m != nil {
		return m.Id_AdmittedSplitSRBs
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_SgNBResourceCoordinationInformation() *SgNBResourceCoordinationInformation {
	if m != nil {
		return m.Id_SgNBResourceCoordinationInformation
	}
	return nil
}

func (m *SgNBAdditionRequestAcknowledge) GetId_RRCConfigIndication() *RRC_Config_Ind {
	if m != nil {
		return m.Id_RRCConfigIndication
	}
	return nil
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList struct {
	Id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item `protobuf:"bytes,1,rep,name=id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item,json=idERABsAdmittedToBeAddedSgNBAddReqAckItem,proto3" json:"id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item,omitempty"`
	XXX_NoUnkeyedLiteral                            struct{}                                        `json:"-"`
	XXX_unrecognized                                []byte                                          `json:"-"`
	XXX_sizecache                                   int32                                           `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{1}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList) GetId_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item() []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item {
	if m != nil {
		return m.Id_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item
	}
	return nil
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item struct {
	E_RAB_ID                    uint32                       `protobuf:"varint,1,opt,name=e_RAB_ID,json=eRABID,proto3" json:"e_RAB_ID,omitempty"`
	En_DC_ResourceConfiguration *EN_DC_ResourceConfiguration `protobuf:"bytes,2,opt,name=en_DC_ResourceConfiguration,json=enDCResourceConfiguration,proto3" json:"en_DC_ResourceConfiguration,omitempty"`
	// Types that are valid to be assigned to ResourceConfiguration:
	//	*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPpresent
	//	*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPnotpresent
	ResourceConfiguration isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration `protobuf_oneof:"resource_configuration"`
	IE_Extensions         []*E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs                         `protobuf:"bytes,5,rep,name=iE_Extensions,json=iEExtensions,proto3" json:"iE_Extensions,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                                                             `json:"-"`
	XXX_unrecognized      []byte                                                               `json:"-"`
	XXX_sizecache         int32                                                                `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{2}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetE_RAB_ID() uint32 {
	if m != nil {
		return m.E_RAB_ID
	}
	return 0
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetEn_DC_ResourceConfiguration() *EN_DC_ResourceConfiguration {
	if m != nil {
		return m.En_DC_ResourceConfiguration
	}
	return nil
}

type isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration interface {
	isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration()
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPpresent struct {
	SgNBPDCPpresent *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent `protobuf:"bytes,3,opt,name=sgNBPDCPpresent,proto3,oneof"`
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPnotpresent struct {
	SgNBPDCPnotpresent *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent `protobuf:"bytes,4,opt,name=sgNBPDCPnotpresent,proto3,oneof"`
}

func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPpresent) isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration() {
}

func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPnotpresent) isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration() {
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetResourceConfiguration() isE_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_ResourceConfiguration {
	if m != nil {
		return m.ResourceConfiguration
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetSgNBPDCPpresent() *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent {
	if x, ok := m.GetResourceConfiguration().(*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPpresent); ok {
		return x.SgNBPDCPpresent
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetSgNBPDCPnotpresent() *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent {
	if x, ok := m.GetResourceConfiguration().(*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPnotpresent); ok {
		return x.SgNBPDCPnotpresent
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) GetIE_Extensions() []*E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs {
	if m != nil {
		return m.IE_Extensions
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPpresent)(nil),
		(*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item_SgNBPDCPnotpresent)(nil),
	}
}

type E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) Reset() {
	*m = E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs{}
}
func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) String() string { return proto.CompactTextString(m) }
func (*E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) ProtoMessage()    {}
func (*E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{3}
}

func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs.Unmarshal(m, b)
}
func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs.Marshal(b, m, deterministic)
}
func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs.Merge(m, src)
}
func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) XXX_Size() int {
	return xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs.Size(m)
}
func (m *E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs proto.InternalMessageInfo

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent struct {
	S1_DL_GTPtunnelEndpoint         *GTPtunnelEndpoint                                               `protobuf:"bytes,1,opt,name=s1_DL_GTPtunnelEndpoint,json=s1DLGTPtunnelEndpoint,proto3" json:"s1_DL_GTPtunnelEndpoint,omitempty"`
	SgNB_UL_GTP_TEIDatPDCP          *GTPtunnelEndpoint                                               `protobuf:"bytes,2,opt,name=sgNB_UL_GTP_TEIDatPDCP,json=sgNBULGTPTEIDatPDCP,proto3" json:"sgNB_UL_GTP_TEIDatPDCP,omitempty"`
	Rlc_Mode                        *RLCMode                                                         `protobuf:"bytes,3,opt,name=rlc_Mode,json=rlcMode,proto3" json:"rlc_Mode,omitempty"`
	DL_Forwarding_GTPtunnelEndpoint *GTPtunnelEndpoint                                               `protobuf:"bytes,4,opt,name=dL_Forwarding_GTPtunnelEndpoint,json=dLForwardingGTPtunnelEndpoint,proto3" json:"dL_Forwarding_GTPtunnelEndpoint,omitempty"`
	UL_Forwarding_GTPtunnelEndpoint *GTPtunnelEndpoint                                               `protobuf:"bytes,5,opt,name=uL_Forwarding_GTPtunnelEndpoint,json=uLForwardingGTPtunnelEndpoint,proto3" json:"uL_Forwarding_GTPtunnelEndpoint,omitempty"`
	MCG_E_RAB_Level_QoS_Parameters  *E_RAB_Level_QoS_Parameters                                      `protobuf:"bytes,6,opt,name=mCG_E_RAB_Level_QoS_Parameters,json=mCGERABLevelQoSParameters,proto3" json:"mCG_E_RAB_Level_QoS_Parameters,omitempty"`
	UL_Configuration                *ULConfiguration                                                 `protobuf:"bytes,7,opt,name=uL_Configuration,json=uLConfiguration,proto3" json:"uL_Configuration,omitempty"`
	IE_Extensions                   []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs `protobuf:"bytes,8,rep,name=iE_Extensions,json=iEExtensions,proto3" json:"iE_Extensions,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}                                                         `json:"-"`
	XXX_unrecognized                []byte                                                           `json:"-"`
	XXX_sizecache                   int32                                                            `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{4}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetS1_DL_GTPtunnelEndpoint() *GTPtunnelEndpoint {
	if m != nil {
		return m.S1_DL_GTPtunnelEndpoint
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetSgNB_UL_GTP_TEIDatPDCP() *GTPtunnelEndpoint {
	if m != nil {
		return m.SgNB_UL_GTP_TEIDatPDCP
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetRlc_Mode() *RLCMode {
	if m != nil {
		return m.Rlc_Mode
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetDL_Forwarding_GTPtunnelEndpoint() *GTPtunnelEndpoint {
	if m != nil {
		return m.DL_Forwarding_GTPtunnelEndpoint
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetUL_Forwarding_GTPtunnelEndpoint() *GTPtunnelEndpoint {
	if m != nil {
		return m.UL_Forwarding_GTPtunnelEndpoint
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetMCG_E_RAB_Level_QoS_Parameters() *E_RAB_Level_QoS_Parameters {
	if m != nil {
		return m.MCG_E_RAB_Level_QoS_Parameters
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetUL_Configuration() *ULConfiguration {
	if m != nil {
		return m.UL_Configuration
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent) GetIE_Extensions() []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs {
	if m != nil {
		return m.IE_Extensions
	}
	return nil
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs struct {
	IdULpDCPSnLength     *PDCPSnLength `protobuf:"bytes,1,opt,name=id_uLpDCPSnLength,json=idULpDCPSnLength,proto3" json:"id_uLpDCPSnLength,omitempty"`
	IdDLPDCPSnLength     *PDCPSnLength `protobuf:"bytes,2,opt,name=id_dLPDCPSnLength,json=idDLPDCPSnLength,proto3" json:"id_dLPDCPSnLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{5}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) GetIdULpDCPSnLength() *PDCPSnLength {
	if m != nil {
		return m.IdULpDCPSnLength
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs) GetIdDLPDCPSnLength() *PDCPSnLength {
	if m != nil {
		return m.IdDLPDCPSnLength
	}
	return nil
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent struct {
	SgNB_DL_GTP_TEIDatSCG          *GTPtunnelEndpoint                                                  `protobuf:"bytes,1,opt,name=sgNB_DL_GTP_TEIDatSCG,json=sgNBDLGTPTEIDatSCG,proto3" json:"sgNB_DL_GTP_TEIDatSCG,omitempty"`
	SecondarySgNB_DL_GTP_TEIDatSCG *GTPtunnelEndpoint                                                  `protobuf:"bytes,2,opt,name=secondary_sgNB_DL_GTP_TEIDatSCG,json=secondarySgNBDLGTPTEIDatSCG,proto3" json:"secondary_sgNB_DL_GTP_TEIDatSCG,omitempty"`
	IE_Extensions                  []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs `protobuf:"bytes,3,rep,name=iE_Extensions,json=iEExtensions,proto3" json:"iE_Extensions,omitempty"`
	XXX_NoUnkeyedLiteral           struct{}                                                            `json:"-"`
	XXX_unrecognized               []byte                                                              `json:"-"`
	XXX_sizecache                  int32                                                               `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{6}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) GetSgNB_DL_GTP_TEIDatSCG() *GTPtunnelEndpoint {
	if m != nil {
		return m.SgNB_DL_GTP_TEIDatSCG
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) GetSecondarySgNB_DL_GTP_TEIDatSCG() *GTPtunnelEndpoint {
	if m != nil {
		return m.SecondarySgNB_DL_GTP_TEIDatSCG
	}
	return nil
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent) GetIE_Extensions() []*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs {
	if m != nil {
		return m.IE_Extensions
	}
	return nil
}

type E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs struct {
	LcId                 *wrappers.UInt32Value `protobuf:"bytes,1,opt,name=lc_id,json=lcId,proto3" json:"lc_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) Reset() {
	*m = E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs{}
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) String() string {
	return proto.CompactTextString(m)
}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) ProtoMessage() {}
func (*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) Descriptor() ([]byte, []int) {
	return fileDescriptor_208f574b8bcb87a2, []int{7}
}

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs.Unmarshal(m, b)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs.Marshal(b, m, deterministic)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs.Merge(m, src)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) XXX_Size() int {
	return xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs.Size(m)
}
func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) XXX_DiscardUnknown() {
	xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs.DiscardUnknown(m)
}

var xxx_messageInfo_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs proto.InternalMessageInfo

func (m *E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs) GetLcId() *wrappers.UInt32Value {
	if m != nil {
		return m.LcId
	}
	return nil
}

func init() {
	proto.RegisterType((*SgNBAdditionRequestAcknowledge)(nil), "streaming_protobufs.SgNBAdditionRequestAcknowledge")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAckList")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_Item")
	proto.RegisterType((*E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs)(nil), "streaming_protobufs.E_RABs_ToBeAdded_SgNBAddReqAck_ItemExtIEs")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresent")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPpresentExtIEs")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresent")
	proto.RegisterType((*E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs)(nil), "streaming_protobufs.E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_SgNBPDCPnotpresentExtIEs")
}

func init() {
	proto.RegisterFile("sgnb_addition_request_acknowledge.proto", fileDescriptor_208f574b8bcb87a2)
}

var fileDescriptor_208f574b8bcb87a2 = []byte{
	// 1106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0xae, 0x9b, 0x9f, 0x86, 0x0d, 0xa5, 0x65, 0x43, 0x12, 0x25, 0x0d, 0x49, 0x30, 0x50, 0x52,
	0x42, 0x6c, 0xe2, 0x5c, 0x94, 0x61, 0x06, 0xa6, 0xb6, 0x64, 0x5c, 0xcd, 0xa8, 0xae, 0xb3, 0x8e,
	0x19, 0x68, 0x66, 0xd8, 0x51, 0xb4, 0x1b, 0x75, 0xa7, 0xf2, 0xae, 0xba, 0x5a, 0x91, 0x84, 0xbb,
	0x3e, 0x01, 0x0f, 0xc1, 0xf0, 0x0c, 0x3c, 0x05, 0x97, 0xdc, 0x70, 0xc3, 0xab, 0x30, 0x5a, 0xc9,
	0x76, 0x1c, 0xab, 0x4e, 0xdc, 0xe4, 0x4e, 0xb3, 0xe7, 0x3b, 0xdf, 0x77, 0xf6, 0xfc, 0xad, 0xc0,
	0x17, 0x91, 0xcf, 0x8f, 0xb0, 0x4b, 0x08, 0x53, 0x4c, 0x70, 0x2c, 0xe9, 0xeb, 0x98, 0x46, 0x0a,
	0xbb, 0xde, 0x2b, 0x2e, 0x4e, 0x02, 0x4a, 0x7c, 0x5a, 0x0a, 0xa5, 0x50, 0x02, 0x2e, 0x44, 0x4a,
	0x52, 0xb7, 0xcb, 0xb8, 0x8f, 0xf5, 0xc1, 0x51, 0x7c, 0x1c, 0xad, 0xae, 0xfb, 0x42, 0xf8, 0x01,
	0x2d, 0xf7, 0x4e, 0xca, 0x27, 0xd2, 0x0d, 0x43, 0x2a, 0xa3, 0xd4, 0x69, 0x75, 0xf9, 0xb4, 0xe2,
	0x86, 0xd8, 0x13, 0xdd, 0xae, 0xe0, 0x58, 0x9d, 0x85, 0xb4, 0x67, 0x58, 0x90, 0xd2, 0xc3, 0x9e,
	0x8f, 0x3d, 0xc1, 0x8f, 0x99, 0x9f, 0x1e, 0x16, 0xff, 0xbd, 0x03, 0xd6, 0xdb, 0x7e, 0xb3, 0x56,
	0xcd, 0xa2, 0x41, 0x69, 0x30, 0xd5, 0x41, 0x2c, 0xf0, 0x4b, 0x00, 0x19, 0xc1, 0xcf, 0x68, 0xb3,
	0x86, 0x3b, 0x75, 0xfc, 0x53, 0xa5, 0xda, 0xc2, 0xb6, 0x65, 0x14, 0x36, 0x0b, 0x5b, 0x77, 0xd1,
	0x07, 0x8c, 0x24, 0x86, 0x4e, 0x3d, 0x39, 0xb6, 0xad, 0x0c, 0x9b, 0x10, 0x9e, 0xc7, 0xde, 0xee,
	0x61, 0x13, 0x43, 0x1f, 0xfb, 0x47, 0x01, 0x94, 0x18, 0xc1, 0x75, 0x8c, 0xaa, 0xb5, 0x08, 0x57,
	0x49, 0x97, 0x29, 0x45, 0x09, 0x3e, 0x10, 0x35, 0x5a, 0x25, 0x84, 0xa6, 0x34, 0x55, 0x42, 0x10,
	0x7d, 0x5d, 0xf5, 0x5e, 0x39, 0x2c, 0x52, 0xc6, 0xd4, 0x66, 0x61, 0x6b, 0xbe, 0xf2, 0xa4, 0x94,
	0x93, 0x97, 0xd2, 0x04, 0x3c, 0xe8, 0x11, 0x23, 0xf5, 0x04, 0xdd, 0x03, 0xf7, 0xb1, 0x23, 0x50,
	0x78, 0x08, 0x56, 0x07, 0x41, 0x36, 0x85, 0xea, 0xf3, 0xeb, 0x80, 0xa6, 0x75, 0x40, 0x1b, 0x6f,
	0x0f, 0x48, 0xc3, 0xd0, 0x52, 0xa6, 0x77, 0xce, 0x5f, 0x93, 0x77, 0xc0, 0x52, 0x96, 0x2e, 0x25,
	0x92, 0x3c, 0x9a, 0x82, 0x2b, 0x97, 0x71, 0x2a, 0x8d, 0x19, 0x4d, 0xbc, 0x9e, 0x4b, 0x6c, 0x36,
	0xb0, 0xa9, 0x6b, 0x88, 0x16, 0xd3, 0x94, 0x5e, 0x70, 0x86, 0x2f, 0xc1, 0x0a, 0x23, 0xd8, 0x94,
	0x4c, 0x31, 0xcf, 0x0d, 0x98, 0x3a, 0xb3, 0x98, 0xeb, 0x73, 0x11, 0x29, 0xe6, 0x45, 0xc6, 0xac,
	0x66, 0xde, 0xce, 0x67, 0xce, 0x75, 0x41, 0x06, 0x23, 0xf9, 0x16, 0x78, 0x08, 0xd6, 0x46, 0x7b,
	0x03, 0xd7, 0x4f, 0x15, 0xe5, 0x11, 0x13, 0xdc, 0xb8, 0xa3, 0xc5, 0xd6, 0x4a, 0x69, 0xcf, 0x96,
	0x7a, 0x4a, 0xa5, 0x8e, 0xcd, 0xd5, 0x5e, 0xe5, 0x47, 0x37, 0x88, 0x29, 0x5a, 0x1e, 0xee, 0xa1,
	0xbe, 0x33, 0xdc, 0x07, 0x1f, 0x31, 0xd2, 0x2f, 0x68, 0x3b, 0x0c, 0x98, 0x6a, 0xa3, 0x5a, 0x64,
	0xcc, 0x8d, 0xc9, 0x4d, 0x1f, 0x85, 0x16, 0x18, 0x19, 0x71, 0x85, 0xbf, 0x17, 0xc0, 0xc3, 0x2c,
	0xe3, 0x88, 0x46, 0x22, 0x96, 0x1e, 0x35, 0x85, 0x90, 0x84, 0x71, 0x37, 0xe9, 0x7e, 0x9b, 0x1f,
	0x0b, 0xd9, 0xd5, 0x9f, 0xc6, 0x7b, 0x5a, 0xe5, 0x9b, 0x7c, 0x95, 0xcb, 0xfd, 0xd1, 0xe7, 0x69,
	0x6d, 0x2e, 0x81, 0xc1, 0x17, 0xba, 0x05, 0x10, 0x32, 0xd3, 0x92, 0xda, 0x9c, 0x30, 0x2f, 0x0d,
	0x00, 0xe8, 0x00, 0x3e, 0xcd, 0x0d, 0x00, 0x21, 0x33, 0xeb, 0x01, 0x6c, 0x73, 0x92, 0xf4, 0x41,
	0x0e, 0x43, 0xf1, 0x9f, 0x02, 0xd8, 0x9e, 0x60, 0x2c, 0xe0, 0x9f, 0x05, 0x50, 0xbe, 0xfa, 0x44,
	0x62, 0x5b, 0xd1, 0xae, 0x51, 0xd8, 0x9c, 0xda, 0x9a, 0xaf, 0x54, 0xaf, 0x33, 0x92, 0x9a, 0xe8,
	0x8a, 0x33, 0x99, 0x40, 0x8b, 0x7f, 0x4d, 0x83, 0xaf, 0x26, 0xe1, 0x86, 0x06, 0x98, 0xa3, 0x7a,
	0x1a, 0xfb, 0x8b, 0x6b, 0x96, 0xa2, 0x6a, 0xcd, 0xb6, 0x60, 0x08, 0x1e, 0x50, 0x8e, 0x2d, 0x13,
	0x0f, 0xea, 0x94, 0x24, 0x31, 0x96, 0x69, 0x0d, 0x6e, 0xeb, 0x1a, 0x7c, 0x9d, 0x7f, 0xbb, 0xe6,
	0x5b, 0xfd, 0xd0, 0x0a, 0xe5, 0x96, 0x99, 0x6b, 0x82, 0xa7, 0xe0, 0x5e, 0xe4, 0x37, 0x6b, 0x2d,
	0xcb, 0x6c, 0x85, 0x92, 0x46, 0x94, 0xf7, 0xd6, 0x9a, 0x73, 0xad, 0x1c, 0xb6, 0x87, 0x39, 0x9f,
	0xde, 0x42, 0x17, 0x65, 0xe0, 0x9b, 0x02, 0x80, 0xbd, 0x33, 0x2e, 0x54, 0x4f, 0x3d, 0xdd, 0x61,
	0xcf, 0x6f, 0x44, 0x7d, 0x40, 0xfb, 0xf4, 0x16, 0xca, 0x11, 0x83, 0x1e, 0xb8, 0xcb, 0xea, 0x83,
	0x05, 0x11, 0x19, 0x33, 0xba, 0x7f, 0xbe, 0x1f, 0xa7, 0x3e, 0xae, 0xb4, 0xf5, 0x53, 0x65, 0xd7,
	0x23, 0xf4, 0x3e, 0xab, 0x0f, 0x38, 0x6b, 0x06, 0x58, 0x92, 0x59, 0xee, 0xb3, 0xd7, 0x2e, 0x4b,
	0x7e, 0x71, 0x1b, 0x3c, 0xba, 0x32, 0x69, 0xf1, 0xef, 0x59, 0xf0, 0xf8, 0x1d, 0xd3, 0x0f, 0x7f,
	0x01, 0xcb, 0xd1, 0x2e, 0xb6, 0x1c, 0xdc, 0x38, 0x68, 0xa9, 0x98, 0x73, 0x1a, 0xd4, 0x39, 0x09,
	0x05, 0xe3, 0x4a, 0x37, 0xe0, 0x7c, 0xe5, 0x61, 0xee, 0x8d, 0x47, 0xd0, 0x68, 0x31, 0xda, 0xb5,
	0x9c, 0x91, 0x63, 0x78, 0x08, 0x96, 0x22, 0xfd, 0xca, 0x6a, 0x05, 0x7c, 0x50, 0xb7, 0x2d, 0x57,
	0x25, 0x01, 0x64, 0x2d, 0x7b, 0x55, 0xfa, 0x85, 0x84, 0xa5, 0x93, 0x08, 0x0c, 0x28, 0xe0, 0x63,
	0x30, 0x27, 0x03, 0x0f, 0x3f, 0x13, 0x84, 0x66, 0xbd, 0xb9, 0x96, 0xbf, 0x85, 0x1c, 0x33, 0xc1,
	0xa0, 0x3b, 0x32, 0xf0, 0x92, 0x0f, 0xc8, 0xc1, 0x06, 0x71, 0xf0, 0x0f, 0x42, 0x9e, 0xb8, 0xc9,
	0xb2, 0xf3, 0x73, 0x6e, 0x3f, 0x3d, 0x51, 0x78, 0x1f, 0x13, 0x67, 0xc0, 0x36, 0x9a, 0x05, 0x0e,
	0x36, 0xe2, 0x4b, 0xf4, 0x66, 0x26, 0xd3, 0x8b, 0xc7, 0xea, 0x49, 0xb0, 0xde, 0x35, 0x1b, 0x38,
	0x7b, 0xd9, 0xe9, 0xaf, 0x34, 0xc0, 0xfb, 0xa2, 0x8d, 0x5b, 0xae, 0x74, 0xbb, 0x54, 0x51, 0xd9,
	0x7b, 0x5d, 0xcb, 0xe3, 0x7e, 0x08, 0x72, 0xdc, 0xd0, 0x4a, 0xd7, 0x6c, 0x24, 0xdb, 0x4f, 0x1b,
	0xf7, 0x45, 0x7b, 0x60, 0x82, 0xcf, 0xc1, 0xfd, 0xd8, 0xc1, 0xc3, 0x6b, 0x29, 0x7d, 0x56, 0x3f,
	0xcb, 0x55, 0xe9, 0x38, 0xc3, 0xab, 0xe8, 0x5e, 0x3c, 0x7c, 0x00, 0x4f, 0x2e, 0x8e, 0xe0, 0x9c,
	0x1e, 0x41, 0x74, 0x93, 0xeb, 0x27, 0x6f, 0x2c, 0x8b, 0xff, 0x15, 0xc0, 0x77, 0xd7, 0xe2, 0x83,
	0x4d, 0xf0, 0x21, 0x23, 0x38, 0x76, 0x42, 0xcb, 0x6c, 0xb5, 0xb9, 0x43, 0xb9, 0xaf, 0x5e, 0x66,
	0xf3, 0xf4, 0x49, 0x6e, 0xf8, 0xad, 0x73, 0x40, 0x74, 0x9f, 0x91, 0xce, 0x90, 0x6b, 0xc6, 0x47,
	0x9c, 0xf3, 0xb0, 0x6c, 0x80, 0xae, 0xc6, 0x67, 0x0d, 0xb9, 0x16, 0xdf, 0x4c, 0x81, 0x6f, 0xdf,
	0x7d, 0x65, 0xc2, 0x9f, 0xc1, 0xa2, 0x1e, 0x6a, 0xeb, 0xfc, 0x50, 0xb7, 0xcd, 0xc6, 0x84, 0x2b,
	0x43, 0xef, 0x5d, 0x6b, 0x30, 0xd3, 0x6d, 0xb3, 0x01, 0x03, 0xb0, 0x11, 0x51, 0x4f, 0x70, 0xe2,
	0xca, 0x33, 0x9c, 0x2f, 0x32, 0xd9, 0xe2, 0x78, 0xd0, 0xa7, 0x6b, 0x8f, 0xaa, 0xfd, 0x76, 0xb1,
	0xc5, 0xa6, 0x74, 0x8b, 0x75, 0x6e, 0xf8, 0x8d, 0xc9, 0xed, 0xb2, 0x18, 0x3c, 0xb9, 0x2e, 0x23,
	0xdc, 0x05, 0x33, 0x81, 0x87, 0x19, 0xc9, 0x12, 0x3f, 0xfe, 0xff, 0x75, 0x3a, 0xf0, 0x6c, 0x52,
	0xdb, 0x7b, 0xb1, 0xeb, 0x53, 0x29, 0x99, 0x2a, 0x89, 0x1d, 0xe9, 0xf2, 0x9d, 0xc8, 0x2b, 0x09,
	0xe9, 0x97, 0x65, 0x59, 0x32, 0x6f, 0x27, 0x0c, 0x54, 0xb9, 0x7f, 0xf5, 0x9d, 0xfe, 0xd5, 0x8f,
	0x66, 0xf5, 0xe7, 0xde, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0x7d, 0x27, 0x29, 0x12, 0x0e,
	0x00, 0x00,
}
