/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_activity_notification.proto */

#ifndef PROTOBUF_C_sgnb_5factivity_5fnotification_2eproto__INCLUDED
#define PROTOBUF_C_sgnb_5factivity_5fnotification_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "x2ap_common_types.pb-c.h"

typedef struct _StreamingProtobufs__SgNBActivityNotification StreamingProtobufs__SgNBActivityNotification;
typedef struct _StreamingProtobufs__SgNBActivityNotificationIEs StreamingProtobufs__SgNBActivityNotificationIEs;


/* --- enums --- */


/* --- messages --- */

struct  _StreamingProtobufs__SgNBActivityNotification
{
  ProtobufCMessage base;
  StreamingProtobufs__SgNBActivityNotificationIEs *protocolies;
};
#define STREAMING_PROTOBUFS__SG_NBACTIVITY_NOTIFICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbactivity_notification__descriptor) \
    , NULL }


struct  _StreamingProtobufs__SgNBActivityNotificationIEs
{
  ProtobufCMessage base;
  uint32_t id_menb_ue_x2ap_id;
  uint32_t id_sgnb_ue_x2ap_id;
  StreamingProtobufs__UserPlaneTrafficActivityReport *id_uecontextleveluserplaneactivity;
  StreamingProtobufs__ERABActivityNotifyItemList *id_erabactivitynotifyitemlist;
  Google__Protobuf__UInt32Value *id_menb_ue_x2ap_id_extension;
};
#define STREAMING_PROTOBUFS__SG_NBACTIVITY_NOTIFICATION__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbactivity_notification__ies__descriptor) \
    , 0, 0, NULL, NULL, NULL }


/* StreamingProtobufs__SgNBActivityNotification methods */
void   streaming_protobufs__sg_nbactivity_notification__init
                     (StreamingProtobufs__SgNBActivityNotification         *message);
size_t streaming_protobufs__sg_nbactivity_notification__get_packed_size
                     (const StreamingProtobufs__SgNBActivityNotification   *message);
size_t streaming_protobufs__sg_nbactivity_notification__pack
                     (const StreamingProtobufs__SgNBActivityNotification   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbactivity_notification__pack_to_buffer
                     (const StreamingProtobufs__SgNBActivityNotification   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBActivityNotification *
       streaming_protobufs__sg_nbactivity_notification__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbactivity_notification__free_unpacked
                     (StreamingProtobufs__SgNBActivityNotification *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__SgNBActivityNotificationIEs methods */
void   streaming_protobufs__sg_nbactivity_notification__ies__init
                     (StreamingProtobufs__SgNBActivityNotificationIEs         *message);
size_t streaming_protobufs__sg_nbactivity_notification__ies__get_packed_size
                     (const StreamingProtobufs__SgNBActivityNotificationIEs   *message);
size_t streaming_protobufs__sg_nbactivity_notification__ies__pack
                     (const StreamingProtobufs__SgNBActivityNotificationIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbactivity_notification__ies__pack_to_buffer
                     (const StreamingProtobufs__SgNBActivityNotificationIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBActivityNotificationIEs *
       streaming_protobufs__sg_nbactivity_notification__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbactivity_notification__ies__free_unpacked
                     (StreamingProtobufs__SgNBActivityNotificationIEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StreamingProtobufs__SgNBActivityNotification_Closure)
                 (const StreamingProtobufs__SgNBActivityNotification *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__SgNBActivityNotificationIEs_Closure)
                 (const StreamingProtobufs__SgNBActivityNotificationIEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbactivity_notification__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbactivity_notification__ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sgnb_5factivity_5fnotification_2eproto__INCLUDED */
