/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sgnb_modification_request.proto */

#ifndef PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/wrappers.pb-c.h"
#include "x2ap_common_types.pb-c.h"
#include "common_types.pb-c.h"
#include "error_cause.pb-c.h"
#include "rrc_cg_config_info.pb-c.h"

typedef struct _StreamingProtobufs__SgNBModificationRequest StreamingProtobufs__SgNBModificationRequest;
typedef struct _StreamingProtobufs__SgNBModificationRequestIEs StreamingProtobufs__SgNBModificationRequestIEs;
typedef struct _StreamingProtobufs__UEContextInformationSgNBModReq StreamingProtobufs__UEContextInformationSgNBModReq;
typedef struct _StreamingProtobufs__UEContextInformationSgNBModReqExtIEs StreamingProtobufs__UEContextInformationSgNBModReqExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqList StreamingProtobufs__ERABsToBeAddedSgNBModReqList;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqItem StreamingProtobufs__ERABsToBeAddedSgNBModReqItem;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent;
typedef struct _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqList StreamingProtobufs__ERABsToBeModifiedSgNBModReqList;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent;
typedef struct _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqList StreamingProtobufs__ERABsToBeReleasedSgNBModReqList;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent;
typedef struct _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs;


/* --- enums --- */


/* --- messages --- */

struct  _StreamingProtobufs__SgNBModificationRequest
{
  ProtobufCMessage base;
  StreamingProtobufs__SgNBModificationRequestIEs *protocolies;
};
#define STREAMING_PROTOBUFS__SG_NBMODIFICATION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbmodification_request__descriptor) \
    , NULL }


struct  _StreamingProtobufs__SgNBModificationRequestIEs
{
  ProtobufCMessage base;
  uint32_t id_menb_ue_x2ap_id;
  uint32_t id_sgnb_ue_x2ap_id;
  StreamingProtobufs__Cause *id_cause;
  Google__Protobuf__BytesValue *id_selectedplmn;
  StreamingProtobufs__HandoverRestrictionList *id_handoverrestrictionlist;
  StreamingProtobufs__TrueOpt *id_scgconfigurationquery;
  StreamingProtobufs__UEContextInformationSgNBModReq *id_ue_contextinformation_sgnbmodreq;
  /*
   *The content of id_MeNBtoSgNBContainer has been specified in 3GPP 38.331 to be CG-ConfigInfo.
   */
  StreamingProtobufs__CGConfigInfo *id_menbtosgnbcontainer;
  Google__Protobuf__UInt32Value *id_menb_ue_x2ap_id_extension;
  StreamingProtobufs__MeNBResourceCoordinationInformation *id_menbresourcecoordinationinformation;
  StreamingProtobufs__SplitSRBs *id_requestedsplitsrbs;
  StreamingProtobufs__SplitSRBs *id_requestedsplitsrbsrelease;
};
#define STREAMING_PROTOBUFS__SG_NBMODIFICATION_REQUEST__IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__sg_nbmodification_request__ies__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _StreamingProtobufs__UEContextInformationSgNBModReq
{
  ProtobufCMessage base;
  StreamingProtobufs__NRUESecurityCapabilities *nrue_securitycapabilities;
  Google__Protobuf__BytesValue *sgnb_securitykey;
  StreamingProtobufs__UEAggregateMaximumBitRate *sgnbueaggregatemaximumbitrate;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqList *e_rabs_tobeadded;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqList *e_rabs_tobemodified;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqList *e_rabs_tobereleased;
  size_t n_ie_extensions;
  StreamingProtobufs__UEContextInformationSgNBModReqExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__UE__CONTEXT_INFORMATION__SG_NBMOD_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__ue__context_information__sg_nbmod_req__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__UEContextInformationSgNBModReqExtIEs
{
  ProtobufCMessage base;
  Google__Protobuf__UInt32Value *id_subscriberprofileidforrfp;
};
#define STREAMING_PROTOBUFS__UE__CONTEXT_INFORMATION_SG_NBMOD_REQ_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__descriptor) \
    , NULL }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs **items;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqItem *id_e_rabs_tobeadded_sgnbmodreq_item;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 4,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} StreamingProtobufs__ERABsToBeAddedSgNBModReqItem__ResourceConfigurationCase;

struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  uint32_t drb_id;
  StreamingProtobufs__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs **ie_extensions;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__descriptor) \
    , 0, 0, NULL, 0,NULL, STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABLevelQoSParameters *full_e_rab_level_qos_parameters;
  StreamingProtobufs__GBRQosInformation *max_mn_admit_e_rab_level_qos_parameters;
  StreamingProtobufs__DLForwarding *dl_forwarding;
  StreamingProtobufs__GTPtunnelEndpoint *menb_dl_gtp_teidatmcg;
  StreamingProtobufs__GTPtunnelEndpoint *s1_ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__RLCMode *id_rlcmode_transferred;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
    , NULL }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABLevelQoSParameters *requested_scg_e_rab_level_qos_parameters;
  StreamingProtobufs__GTPtunnelEndpoint *menb_ul_gtp_teidatpdcp;
  StreamingProtobufs__GTPtunnelEndpoint *secondary_menb_ul_gtp_teidatpdcp;
  StreamingProtobufs__RLCMode *rlc_mode;
  StreamingProtobufs__ULConfiguration *ul_configuration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__PDCPSnLength *id_ulpdcpsnlength;
  StreamingProtobufs__PDCPSnLength *id_dlpdcpsnlength;
  StreamingProtobufs__DuplicationActivation *id_duplicationactivation;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_ADDED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
    , NULL, NULL, NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs **items;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem *id_e_rabs_tobemodified_sgnbmodreq_item;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 3,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem__ResourceConfigurationCase;

struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  StreamingProtobufs__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs **ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__descriptor) \
    , 0, NULL, 0,NULL, STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABLevelQoSParameters *full_e_rab_level_qos_parameters;
  StreamingProtobufs__GBRQosInformation *max_mn_admit_e_rab_level_qos_parameters;
  StreamingProtobufs__GTPtunnelEndpoint *menb_dl_gtp_teidatmcg;
  StreamingProtobufs__GTPtunnelEndpoint *s1_ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__RLCStatus *id_rlc_status;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
    , NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABLevelQoSParameters *requested_scg_e_rab_level_qos_parameters;
  StreamingProtobufs__GTPtunnelEndpoint *menb_ul_gtp_teidatpdcp;
  StreamingProtobufs__ULConfiguration *ul_configuration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , NULL, NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__PDCPSnLength *id_ulpdcpsnlength;
  StreamingProtobufs__PDCPSnLength *id_dlpdcpsnlength;
  StreamingProtobufs__GTPtunnelEndpoint *id_secondarymenbulgtpteidatpdcp;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_MODIFIED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
    , NULL, NULL, NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqList
{
  ProtobufCMessage base;
  size_t n_items;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs **items;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs
{
  ProtobufCMessage base;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem *id_e_rabs_tobereleased_sgnbmodreq_item;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__descriptor) \
    , NULL }


typedef enum {
  STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET = 0,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPPRESENT = 3,
  STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION_SG_NBPDCPNOTPRESENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION)
} StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem__ResourceConfigurationCase;

struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem
{
  ProtobufCMessage base;
  uint32_t e_rab_id;
  StreamingProtobufs__ENDCResourceConfiguration *en_dc_resourceconfiguration;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs **ie_extensions;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem__ResourceConfigurationCase resource_configuration_case;
  union {
    StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *sgnbpdcppresent;
    StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *sgnbpdcpnotpresent;
  };
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__descriptor) \
    , 0, NULL, 0,NULL, STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM__RESOURCE_CONFIGURATION__NOT_SET, {0} }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__ITEM_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__descriptor) \
     }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent
{
  ProtobufCMessage base;
  StreamingProtobufs__GTPtunnelEndpoint *dl_gtptunnelendpoint;
  StreamingProtobufs__GTPtunnelEndpoint *ul_gtptunnelendpoint;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__descriptor) \
    , NULL, NULL, 0,NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor) \
     }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent
{
  ProtobufCMessage base;
  size_t n_ie_extensions;
  StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs **ie_extensions;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor) \
    , 0,NULL }


struct  _StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs
{
  ProtobufCMessage base;
};
#define STREAMING_PROTOBUFS__E__RABS__TO_BE_RELEASED__SG_NBMOD_REQ__SG_NBPDCPNOTPRESENT_EXT_IES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor) \
     }


/* StreamingProtobufs__SgNBModificationRequest methods */
void   streaming_protobufs__sg_nbmodification_request__init
                     (StreamingProtobufs__SgNBModificationRequest         *message);
size_t streaming_protobufs__sg_nbmodification_request__get_packed_size
                     (const StreamingProtobufs__SgNBModificationRequest   *message);
size_t streaming_protobufs__sg_nbmodification_request__pack
                     (const StreamingProtobufs__SgNBModificationRequest   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbmodification_request__pack_to_buffer
                     (const StreamingProtobufs__SgNBModificationRequest   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBModificationRequest *
       streaming_protobufs__sg_nbmodification_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbmodification_request__free_unpacked
                     (StreamingProtobufs__SgNBModificationRequest *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__SgNBModificationRequestIEs methods */
void   streaming_protobufs__sg_nbmodification_request__ies__init
                     (StreamingProtobufs__SgNBModificationRequestIEs         *message);
size_t streaming_protobufs__sg_nbmodification_request__ies__get_packed_size
                     (const StreamingProtobufs__SgNBModificationRequestIEs   *message);
size_t streaming_protobufs__sg_nbmodification_request__ies__pack
                     (const StreamingProtobufs__SgNBModificationRequestIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__sg_nbmodification_request__ies__pack_to_buffer
                     (const StreamingProtobufs__SgNBModificationRequestIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__SgNBModificationRequestIEs *
       streaming_protobufs__sg_nbmodification_request__ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__sg_nbmodification_request__ies__free_unpacked
                     (StreamingProtobufs__SgNBModificationRequestIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__UEContextInformationSgNBModReq methods */
void   streaming_protobufs__ue__context_information__sg_nbmod_req__init
                     (StreamingProtobufs__UEContextInformationSgNBModReq         *message);
size_t streaming_protobufs__ue__context_information__sg_nbmod_req__get_packed_size
                     (const StreamingProtobufs__UEContextInformationSgNBModReq   *message);
size_t streaming_protobufs__ue__context_information__sg_nbmod_req__pack
                     (const StreamingProtobufs__UEContextInformationSgNBModReq   *message,
                      uint8_t             *out);
size_t streaming_protobufs__ue__context_information__sg_nbmod_req__pack_to_buffer
                     (const StreamingProtobufs__UEContextInformationSgNBModReq   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__UEContextInformationSgNBModReq *
       streaming_protobufs__ue__context_information__sg_nbmod_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__ue__context_information__sg_nbmod_req__free_unpacked
                     (StreamingProtobufs__UEContextInformationSgNBModReq *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__UEContextInformationSgNBModReqExtIEs methods */
void   streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__init
                     (StreamingProtobufs__UEContextInformationSgNBModReqExtIEs         *message);
size_t streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__get_packed_size
                     (const StreamingProtobufs__UEContextInformationSgNBModReqExtIEs   *message);
size_t streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__pack
                     (const StreamingProtobufs__UEContextInformationSgNBModReqExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__UEContextInformationSgNBModReqExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__UEContextInformationSgNBModReqExtIEs *
       streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__free_unpacked
                     (StreamingProtobufs__UEContextInformationSgNBModReqExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqList methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqList         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqList   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqList   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqList *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqItem methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItem         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItem   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqItem *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqList methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqList         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqList   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqList   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqList *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqList methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqList         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqList   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqList   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqList   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqList *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqList *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *message,
                      ProtobufCAllocator *allocator);
/* StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs methods */
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__init
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs         *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__get_packed_size
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      uint8_t             *out);
size_t streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__pack_to_buffer
                     (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs   *message,
                      ProtobufCBuffer     *buffer);
StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *
       streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__free_unpacked
                     (StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*StreamingProtobufs__SgNBModificationRequest_Closure)
                 (const StreamingProtobufs__SgNBModificationRequest *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__SgNBModificationRequestIEs_Closure)
                 (const StreamingProtobufs__SgNBModificationRequestIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__UEContextInformationSgNBModReq_Closure)
                 (const StreamingProtobufs__UEContextInformationSgNBModReq *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__UEContextInformationSgNBModReqExtIEs_Closure)
                 (const StreamingProtobufs__UEContextInformationSgNBModReqExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqList_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqList *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqItem_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeAddedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqList_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqList *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeModifiedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqList_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqList *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItem *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqItemExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPpresentExtIEs *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresent *message,
                  void *closure_data);
typedef void (*StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs_Closure)
                 (const StreamingProtobufs__ERABsToBeReleasedSgNBModReqSgNBPDCPnotpresentExtIEs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbmodification_request__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__sg_nbmodification_request__ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__ue__context_information__sg_nbmod_req__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__ue__context_information_sg_nbmod_req_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_added__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_modified__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__list__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__item_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcppresent_ext_ies__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent__descriptor;
extern const ProtobufCMessageDescriptor streaming_protobufs__e__rabs__to_be_released__sg_nbmod_req__sg_nbpdcpnotpresent_ext_ies__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sgnb_5fmodification_5frequest_2eproto__INCLUDED */
