apiVersion: v1
kind: Service
metadata:
  name: {{ include "gnbe2-oran-simu.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gnbe2-oran-simu.name" . }}
    helm.sh/chart: {{ include "gnbe2-oran-simu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: sctp
      protocol: SCTP
      name: sctp
  selector:
    app.kubernetes.io/name: {{ include "gnbe2-oran-simu.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
